      Program Main
      Integer JSTOP
      character*80 filen
      integer :: clock0, clock1, clockmax, clockrate, ticks
      real    :: secs
      filen = 'vs2drt.fil'
      JSTOP = 0
!     SET UP TO READ FROM DATA FILE GENERATED BY VS2DTI
      call system_clock(count_max=clockmax, count_rate=clockrate)
      call system_clock(clock0)
      call SETUP(filen)
 10   CALL STEP(JSTOP)
      IF (JSTOP.EQ.0) GOTO 10  
      ! call system_clock(clock1)

      !ticks = clock1-clock0
      !ticks = mod(ticks+clockmax, clockmax)   ! reset negative numbers
      !secs = float(ticks)/float(clockrate)
      call system_clock(clock1, clockrate, clockmax)
      secs = real( clock1 - clock0) / real(clockrate)
      print*,'Code took ', secs, ' seconds' 
      stop
      end
      !include 'd_modules.inc'
      SUBROUTINE SETUP( filen)
! *** THIS SUBROUTINE IS THE FIRST HALF OF THE ORIGINAL MAIN CODE
! *** THAT READS THE SIMULATION DATA
!***    12/1/98
!
!
!******
!VSEXEC
!******
!-----------------------------------------------------------------
!         ************ PROGRAM VS2DRT *********************
!
!   PROGRAM TO SOLVE FOR:
!      TWO DIMENSIONAL VERTICAL SECTION OR CYLINDRICAL THREE
!          DIMENSIONAL FLUID FLOW AND REACTIVE TRANSPORT UNDER
!         VARIABLY SATURATED CONDITIONS
!
!       FLUID FLOW IS SOLVED FOR BY AN IMPLICIT FINITE DIFFERENCE
!          FORMULATION OF THE COMBINED RICHARDS AND COOPER-JACOB
!          EQUATIONS FOR FLUID CONTINUITY.
!
!.................................................................
!
!      SPECIFICATIONS FOR ARRAYS AND SCALARS
!
      use BF
      use COORDIN
      use DISCH
      use DUMM
      use DUMM1
      use DUMM2
      use DUMM3
      use EQUAT
      use EQUATS
      use HCON
      use IDUMM
      use IHDUMM
      use ISDUMM
      use ITEMBLO
      use ITEMTXB
      use JTXX
      use KCON
      use MPROP
      use PHREECC
      use PIT
      use PLOTT
      use PRESS
      use PRICON
      use PTET
      use RPROPSH
      use RSPAC
      use SCON
      use SIP
      use SOLINDEX
      use SOLMASS
      use SPFC
      use TEMP
      use TEMPCC
      use TRXV
      use TRXX
      use TRXXH
      use TRXY1
      use TRXY2

      use rspac
      use kcon
      use mprop
      use press
      use disch
      use hcon
      use equat
      use jtxx
      use dumm
      use ptet
      use trxx
      use trxy1
      use pit
      use sip
      use plott
      use spfc
      use rpropsh
      use scon
      use equats
      use trxy2
      use trxxh
      use trxv
      use temp
      use solmass
      use tempcc
      use compnam
      use pricon
      use coordin
      use solindex    
      use phreecc
      use react
      USE vs2dt_rm
      USE PhreeqcRM
      IMPLICIT DOUBLE PRECISION (A-H,P-Z)
      COMMON/ISPAC/NLY,NLYY,NXR,NXRR,NNODES,Nsol,Nodesol
      COMMON/PND/POND
      COMMON/WGT/WUS,WDS
      COMMON/SCN1/TMPX,TMLT,DLTMX,DLTMIN,TRED
      COMMON/TCON/STIM,DSMAX,KTIM,NIT,NIT1,KP,NIT3
      COMMON/JCON/JSTOP,JFLAG,jflag1
      LOGICAL TRANS,TRANS1,TRANS2,SSTATE
      COMMON/TRXY/EPS1,EPS2,EPS3,TRANS,TRANS1,TRANS2,SSTATE,MB9(99),NMB9
      LOGICAL RAD,BCIT,ETSIM,SEEP,ITSTOP,CIS,CIT,GRAV
      LOGICAL F7P,F11P,F8P,F9P,F6P,PRNT,o9p,o11p,o12p,o13p,F14P, &
      F15P,F16P,F17P,F18P,F19P
      LOGICAL THPT,SPNT,PPNT,HPNT,VPNT
      COMMON/LOG1/RAD,BCIT,ETSIM,SEEP,ITSTOP,CIS,CIT,GRAV
      COMMON/LOG2/F7P,F11P,F8P,F9P,F6P,PRNT,o9p,o11p,o12p,o13p,F14P, &
      F15P,F16P,F17P,F18P,F19P
      COMMON/LOG4/THPT,SPNT,PPNT,HPNT,VPNT
      CHARACTER*80 TITL,filen,f5,f6,f7,f8,f9,f10,f11,f12,f14, &
      f15,f16,f17,blank,f18,f19
      CHARACTER*6 ZUNIT,CUNX,HUNX
      CHARACTER*7 TUNIT
      COMMON/SCHAR/TITL,ZUNIT,TUNIT,CUNX,HUNX
      COMMON/MASSB/ BL(99),bcmft,bcmth,bl29I,bl29IT,bl29O,bl29OT,  &
      bl95I,bl95IT,bl95o,bl95OT
      integer hydraulicFunctionType,iuTemperature,iuHead,iuConcentration
      common/functiontype/ hydraulicFunctionType
!      COMMON/VERSION/VER2P5
!     LOGICAL VER2P5
      common/iuNumber/ iuHead, iuConcentration,iuTemperature
! *** NEXT STATEMENT CHANGED FROM SAVE TO COMMON
      COMMON/TTT/IFET,IFET1,NITT,NITT1,NITT2
      common/elimit/elimit1,elimit2
      real*8 ang
      integer NHTPROP,NSTPROP
      COMMON/TRANNSPROP/NHTPROP,NSTPROP
      LOGICAL HEAT,SOLUTE,FLOW
      COMMON/TRANSTYPE/HEAT,SOLUTE
      COMMON/TCON1/NIS,NIS1,NIS3
      COMMON/TTT1/NISS,NISS1,NISS2
      COMMON/FLO/FLOW
      COMMON/SCON1/ITESTS
      CHARACTER*80 CHEMFILE,DATABASEFILE,PREFIX
      COMMON/SOLCHAR/CHEMFILE,DATABASEFILE,PREFIX
      logical axes(2) 
      common/axis/axes
      common/conversion/CNVTM,CNVTMI     
      CHARACTER*10 SCOMPNAME(50)
      common/ITEMK/KNLY,KNXR,KNNODE
      !!@@include 'd_kdum.inc'
      integer, allocatable::KDUM(:,:)
!     include 'c_kdum.inc'
! *** Set version, hydraulic function type, and sorption type
!--------------------------------------------------------------------------------------------
!

!   open files 
!
      iuHead = 5
      iuConcentration = 5
      GRAV = .FALSE.
      blank = ' '
      open(12,file='fort.12',FORM='UNFORMATTED',ACTION='WRITE',  &
      POSITION='REWIND')
      open(2,file=filen)
      read(2,9090)f5
      read(2,9090)f6
      read(2,9090)f7
      read(2,9090)f8
      read(2,9090)f9
      read(2,9090)f11
      read(2,9090)f14
      read(2,9090)f15
      read(2,9090)f16
      read(2,9090)f17
      read(2,9090)f18
      read(2,9090)f19
      read(2,9090,end=9088)f10
      iInitial = index(f10,'#')
      if (iInitial.ne.0) go to 9088
      if(f5.ne.f10.and.f10.ne.blank) then
       open(13,file='fort.13',FORM='UNFORMATTED')
       open(10,file=f10)
!       iuHead = 10
      end if
      read(2,9090,end=9089)f12
 9089 continue     
 9088 open(5,file=f5)
      open(6,file=f6)
      open(7,file=f7)
      open(8,file=f8)
      open(9,file=f9)
      open(11,file=f11)
      open(14,file=f14)
      open(15,file=f15)
      open(16,file=f16)
      open(17,file=f17)
      open(18,file=f18)
      open(19,file=f19)
 9090 format(a80)
!
!-------------------------------------------------------------------
!
!  ---- READ AND WRITE PROBLEM TITLE AND SPACE AND TIME CONSTANTS
!
      JSTOP=0
      READ (05,4000) TITL
      READ (5,*) TMAX,STIM,ANG
      READ (05,4010) ZUNIT
      READ (05,4011) TUNIT
      READ (05,4010) CUNX
      READ (05,4010) HUNX
      IF(TUNIT.EQ.'s'.or.TUNIT.EQ.'seconds')then
      CNVTM= 1.D0
      ELSE IF (TUNIT.EQ.'min'.or.TUNIT.EQ.'minutes')then
      CNVTM=60.D0
      ELSE IF (TUNIT.EQ.'h'.or.TUNIT.EQ.'hours')then
      CNVTM=3600.D0
      ELSE IF (TUNIT.EQ.'d'.or.TUNIT.EQ.'days')then
      CNVTM=864000.D0
      ELSE IF (TUNIT.EQ.'yr'.or.TUNIT.EQ.'years')then
      CNVTM=3.155815D7
      END IF
      CNVTMI= 1.D0/ CNVTM    
      READ (05,*) NXR,NLY
      if(NXR .GT. 2) THEN 
      axes(1)= .true.
      ELSE IF (NXR .EQ. 2)then
      axes(1)= .false.
      END IF
      if(NLY .GT. 2) THEN 
      axes(2)= .true.
      ELSE IF (NLY.EQ. 2)then
      axes(2)= .false.
      END IF
      READ (05,*) NRECH,NUMT
!
!  o13p triggers high precisions output
!  o12p triggers p,c unformatted output to file 12
!  o9p = t for MB output only at specified times
!  o11p = t for obsPoint output only at specified times
!
      if(NUMT.lt.0) then
       numt = -numt
       o13p = .TRUE.
      else
       o13p = .FALSE.
      end if
      if (nrech.lt.0) then
       nrech = -nrech
       o12p = .TRUE.
      else
       o12p = .FALSE.
      end if
      WRITE (06,4060)
      WRITE (06,4070) TITL,TMAX,TUNIT,STIM,NRECH,NUMT,NLY,NXR
      WRITE(06,4080) ANG
      IF(ANG.GT.90.0D0.OR.ANG.LT.-90.0D0)THEN
      WRITE(06,4090)
      jstop=2
      return
      END IF
      READ (05,*) RAD,ITSTOP,HEAT,SOLUTE
      IF (SOLUTE) then
      READ (05,4001) CHEMFILE
      READ (05,4001) DATABASEFILE
      READ (05,4001) PREFIX
      End if
      IF(HEAT.OR.SOLUTE) then 
        TRANS = .TRUE.
        FLOW = .FALSE.
        else
        TRANS = .FALSE.
        FLOW = .TRUE.
      END IF
      IF(TRANS) READ(05,*)CIS,CIT
      IF(SOLUTE)THEN
      READ (05,*)NPRCONC,NPSCRN,IPRNTCHE,INPRXZ,IPOUT
  !    DO 5 I=1,NNODES
  !    NPRCHEM(I)= IPRNTCHE
  !    NPRCHXZ(I)= INPRXZ
  !5   CONTINUE
      END IF     
      READ (05,*) F11P,F7P,F8P,F9P,F6P
      READ (05,*) THPT,SPNT,PPNT,HPNT,VPNT
      WRITE (06,4100) F8P,ITSTOP,F7P,F11P,F9P,F6P
      WRITE (06,4110) THPT,SPNT,PPNT,HPNT,VPNT   
      NLYY=NLY-1
      NXRR=NXR-1
      NNODES=NLY*NXR
      Nsol=0
      IF (SOLUTE)then
          CALL CreateRM(SOLUTE, NNODES,  PREFIX, DATABASEFILE, CHEMFILE, nSol)
          !#CALL PHREEQC_MAIN(SOLUTE,CHEMFILE,DATABASEFILE,PREFIX)
          !#SCOMPNAME= "          "
          !#CALL COUNT_ALL_COMPONENTS(Nsol, SCOMPNAME)
          do i = 1, nSol
              status = RM_GetComponent(rm_id, i, scompname(i))
          enddo
          Nodesol= NNODES*Nsol  
      END IF
      IF(PPNT.OR.HPNT)THEN
        F14P=.TRUE.
      ELSE
        F14P=.false.
      END IF    
      IF(SOLUTE)THEN
        F15P=.TRUE.
      ELSE
        F15P=.false.
      END IF
      IF(HEAT)THEN
        F16P=.TRUE.
      ELSE
        F16P=.false.
      END IF  
      IF(VPNT)THEN
        F17P=.TRUE.
      ELSE
        F17P=.false.
      END IF
      IF(THPT)THEN
        F18P=.TRUE.
      ELSE
        F18P=.false.
      END IF
      IF(SPNT)THEN
        F19P=.TRUE.
      ELSE
        F19P=.false.
      END IF
      KNLY=NlY-2
      KNXR=NXR-2
      KNNODE=KNLY*KNXR
      !!@@include 'd_arrays.inc' 
!     allocate arrays
      allocate(DELZ(NLY),DZZ(NLY),DXR(NXR),RX(NXR))
      allocate(HX(NNODES),NTYP(NNODES))
      allocate(THETA(NNODES),THLST(NNODES),SATUR(NNODES),POROSITY(NNODES))
      allocate(P(NNODES),PXXX(NNODES),THEAD(NNODES))
      allocate(Q(NNODES),QQ(NNODES))
      allocate(HCND(NNODES),HKLL(NNODES),HKTT(NNODES))
      allocate(A(NNODES),B(NNODES),C(NNODES),D(NNODES),E(NNODES),  &
         RHS(NNODES),XI(NNODES))
     allocate(AS(NNODES),BS(NNODES),CS(NNODES),DS(NNODES),ES(NNODES),  &
         RHSS(NNODES),XIS(NNODES))
      allocate(JTEX(NNODES))
      allocate(DUM(NNODES),PDUM(KNXR))
      allocate(DPTH(NNODES),RT(NNODES))
      allocate(DX1(NNODES),DX2(NNODES),DZ1(NNODES),DZ2(NNODES),  &
          TT(NNODES),TTOLD(NNODES),TS(NNODES),  &
         QT(NNODES),NHTYP(NNODES))
     allocate(VX(NNODES),VZ(NNODES))
     allocate(RHO(NNODES),RHOOLD(NNODES))
     allocate(DXS1(NNODES),DXS2(NNODES),DZS1(NNODES),DZS2(NNODES),  &
          CC(Nsol,NNODES),CCOLD(Nsol,NNODES),CSS(Nsol,NNODES),  &
          QS(NNODES),NCTYP(NNODES),CONC(Nsol))
      allocate(AO(NNODES),BO(NNODES),CO(NNODES),DO(NNODES),EO(NNODES))
      allocate(AOC(NNODES),BOC(NNODES),COC(NNODES),DOC(NNODES),EOC(NNODES))
      allocate(PITT(NNODES))
      allocate(DEL(NNODES),ETA(NNODES),V(NNODES))
      allocate(TempC(NNODES))
      allocate(XNODE(NNODES),ZNODE(NNODES))
      allocate(phreeC(Nodesol))
      allocate(CMIXFARC(7,NNODES),BCSOL(Nsol),INDSOL1(7,NNODES),INDSOL2(7,NNODES))
	  allocate(ic1_reordered(nnodes,7))
      allocate(NPRCHEM(NNODES),NPRCHXZ(NNODES))
      allocate(BLSOL(Nsol,36),bl62I(Nsol),bl62IT(Nsol),bl62O(Nsol),bl62OT(Nsol), &
             bcmtt(Nsol),bcmt(Nsol),bcmtr(Nsol),bltemp36(Nsol),bltemp39(Nsol), &
             bltemp42(Nsol),bltemp45(Nsol),bltemp60(Nsol))
      allocate(COMPNAME(Nsol))       
      allocate(CCBR(Nsol,NNODES),CCAR(Nsol,NNODES))      
      IF (SOLUTE) THEN  
      DO 7 I=1,Nsol 
      compname(I)  = scompname(I)
      WRITE(06,4012)compname(I)
   7  CONTINUE       
      END IF 
!      include 'c_arrays.inc'
! *** SET ALL ARRAYS TO ZERO
      DO 710 I=1, NLY
      DELZ(I) = 0.0D0
      DZZ(I) = 0.0D0
 710  CONTINUE
      DO 715 I=1, NXR
      DXR(I) = 0.0D0
      RX(I) = 0.0D0
 715  CONTINUE
      do 8 I=1, Nodesol
      phreeC(I)=0.d0
  8   continue
      DO 711 I=1, NNODES
      XNODE(I)= 0.0D0
      ZNODE(I)= 0.0D0  
      HX(I) = 0.0D0
      NTYP(I) = 0
      THETA(I) = 0.0D0
      THLST(I) = 0.0D0
      SATUR(I)=0.0D0
      P(I) = 0.0D0
      PXXX(I) = 0.0D0
      THEAD(I)=0.0D0
      Q(I) = 0.0D0
      QQ(I) = 0.0D0
      HCND(I) = 0.0D0
      HKLL(I) = 0.0D0
      HKTT(I) = 0.0D0
      A(I) = 0.0D0
      B(I) = 0.0D0
      C(I) = 0.0D0
      D(I) = 0.0D0
      E(I) = 0.0D0
      RHS(I) = 0.0D0
      XI(I) = 0.0D0
      AS(I) = 0.0D0
      BS(I) = 0.0D0
      CS(I) = 0.0D0
      DS(I) = 0.0D0
      ES(I) = 0.0D0
      RHSS(I) = 0.0D0
      JTEX(I) = 0
      DUM(I) = 0.0D0
      DPTH(I) = 0.0D0
      RT(I) = 0.0D0
      DX1(I) = 0.0D0
      DX2(I) = 0.0D0
      DZ1(I) = 0.0D0
      DZ2(I) = 0.0D0
      DXS1(I) = 0.0D0
      DXS2(I) = 0.0D0
      DZS1(I) = 0.0D0
      DZS2(I) = 0.0D0
      VX(I) = 0.0D0
      VZ(I) = 0.0D0
      TT(I) = 0.0D0
      TTOLD(I) = 0.0D0
      TS(I) = 0.0D0
      QT(I) = 0.0D0
      QS(I) = 0.0D0
      TempC(I)=0.0D0
      NHTYP(I) = 0
      NCTYP(I) = 0
      AO(I) = 0.0D0
      BO(I) = 0.0D0
      CO(I) = 0.0D0
      DO(I) = 0.0D0
      EO(I) = 0.0D0
      AOC(I) = 0.0D0
      BOC(I) = 0.0D0
      COC(I) = 0.0D0
      DOC(I) = 0.0D0
      EOC(I) = 0.0D0
      PITT(I) = 0.0D0
      XIS(I)=0.0D0
      RHO(I) = 0.0D0
      RHOOLD(I) = 0.0D0
      NPRCHEM(I) = 0
      NPRCHXZ(I) = 0 
 711  CONTINUE
      DO 714 I=1, NNODES
      DO 713 M=1, Nsol
      CC(M,I) = 0.0D0
      CCOLD(M,I) = 0.0D0
      CSS(M,I) = 0.0D0
      CCBR(M,I)= 0.0D0
      CCAR(M,I)= 0.0D0
 713  CONTINUE  
 714  CONTINUE
      DO 801 J=1, NNODES
      DO 800 I=1, 7
      INDSOL1(I,J)= -1
      INDSOL2(I,J)= -1
      CMIXFARC(I,J) = 0.0D0
 800  CONTINUE
 801  CONTINUE
      DO 712 I=1,99
      BL(I)=0.0D0
 712  CONTINUE
      bcmft = 0.0D0
      bcmht = 0.0D0
      bl29I = 0.0D0
      bl29IT = 0.0D0
      bl29O = 0.0D0
      bl29OT = 0.0D0
      bl95I = 0.0D0
      bl95IT = 0.0D0
      bl95O = 0.0D0
      bl95OT = 0.0D0
      DO 717 M=1,Nsol
      bl62I(M) = 0.0D0
      bl62IT(M) = 0.0D0
      bl62O(M)= 0.0D0
      bl62OT(M) = 0.0D0
      DO 716 J=1,36
      BLSOL(M,J)= 0.0D0
      bcmtt(M)=0.0D0
 716  CONTINUE
 717  CONTINUE
      
      DO 5 I=1,NNODES
      NPRCHEM(I)= IPRNTCHE
      NPRCHXZ(I)= INPRXZ
5     CONTINUE   
      
!
!   ESTABLISH HORIZONTAL OR RADIAL SPACING
!
      READ (05,*) IFAC,FACX
      IF(IFAC.GT.0) GO TO 20
!
!   READ IN SPACING FOR EACH COLUMN
!
      READ (05,*) (DXR(K),K=1,NXR)
      DO 10 K=1,NXR
   10 DXR(K)=DXR(K)*FACX
      GO TO 60
   20 IF(IFAC.EQ.2) GO TO 40
      DO 30 K=1,NXR
   30 DXR(K)=FACX
      GO TO 60
!
!  IF IFAC=2, HORIZONTAL NODE SPACING IS INCREMENTED BY A CONSTANT
!    MULTIPLIER UNTIL A USER-SPECIFIED MAXIMUM IS REACHED, WHERE-
!    UPON THE SPACING BECOMES CONSTANT
!
   40 READ (05,*) XMULT,XMAX
      DXR(1)=FACX
      DXR(2)=FACX
      DO 50 K=3,NXRR
      DXR(K)=DXR(K-1)*XMULT
      IF(DXR(K) .GT. XMAX)DXR(K)=XMAX
   50 CONTINUE
      DXR(NXR)=DXR(NXRR)
!
!   ESTABLISH VERTICAL SPACING
!
   60 READ (05,*) JFAC,FACZ
      IF(JFAC.GT.0) GO TO 80
!
!   READ IN VERTICAL SPACINGS INDIVIDUALLY
!
      READ (05,*) (DELZ(K),K=1,NLY)
      DO 70 K=1,NLY
   70 DELZ(K)=DELZ(K)*FACZ
      GO TO 120
   80 IF(JFAC.EQ.2) GO TO 100
      DO 90 K=1,NLY
   90 DELZ(K)=FACZ
      GO TO 120
!
!   ESTABLISH VERTICAL SPACING BY PROGRESSION, AS ABOVE FOR HORIZ.
!
  100 READ (05,*) ZMULT,ZMAX
      DELZ(1)=FACZ
      DELZ(2)=FACZ
      DO 110 K=3,NLYY
      DELZ(K)=DELZ(K-1)*ZMULT
      IF(DELZ(K) .GT. ZMAX)DELZ(K)=ZMAX
  110 CONTINUE
      DELZ(NLY)=DELZ(NLYY)
  120 CONTINUE
!
!    DETERMINE HORIZONTAL AND VERTICAL COORDINATES
!
      RX(1)=-0.5D0 *DXR(1)
      DO 130 N=2,NXR
      RX(N)=RX(N-1)+0.5D0 *(DXR(N-1)+DXR(N))
  130 CONTINUE
      DZZ(1)=-0.5D0 *DELZ(1)
      DO 140 J=2,NLY
  140 DZZ(J)=DZZ(J-1)+0.5D0 *(DELZ(J-1)+DELZ(J))
      DO 11 I=1,NNODES
      IMOD=MOD(I,NLY)
      XNODE(I)= (I-IMOD)/NLY + MIN(1,IMOD)
      IF(IMOD .EQ.0) THEN
      ZNODE(I)=NLY
      ELSE
      ZNODE(I)= IMOD
      END IF      
  11  CONTINUE
!      DO 12 I=1,NNODES 
!      write(6,*)"XNODE(",I,")=", XNODE(I),"ZNODE(",I,")=", ZNODE(I)
!  12  CONTINUE
      WRITE (06,4120) ZUNIT,(DELZ(K),K=1,NLY)
      WRITE (06,4130) ZUNIT,(DXR(K),K=1,NXR)
      PI=3.141592654D0
      PI2=PI+PI
      ANG=ANG/360.0D0
      IF(ANG.EQ.0.0D0) THEN
      CS1=1.0D0
      CS2=0.0D0
      ELSE
      IF(ANG.EQ.0.25D0.OR.ANG.EQ.-0.25D0) THEN
      CS1=0.0D0
      ELSE
      CS1=DCOS(ANG*PI2)
      END IF
      CS2=-DSIN(ANG*PI2)
      END IF
!
!    READ DATA FOR MONITORING TIMES AND POINTS
!
      NPLT=0
      o9p = .false.
      o11p = o9p
      IF(F8P) THEN
      READ (05,*) NPLT
      !!@@include 'd_obst.inc'
      allocate(PLTIM(NPLT+1))
!      include 'c_obst.inc'
      IF(NPLT.EQ.0)NPLT=1
      READ (05,*) (PLTIM(K),K=1,NPLT)
      WRITE (06,4140) (PLTIM(K),K=1,NPLT)
      else
      !!@@include 'd_obst.inc'
      allocate(PLTIM(NPLT+1))      
      END IF
      IF(F11P) THEN
      READ (05,*) NOBS
      if (nobs.lt.0) then
       nobs = -nobs
       o11p = .true.
      end if
      !!@@include 'd_obsp.inc'
      allocate(IJOBS(NOBS))
      if (allocated(KDUM)) deallocate(KDUM)
      allocate(KDUM(NOBS,2))      
      READ (05,*) ((KDUM(K,J),J=1,2),K=1,NOBS)
      WRITE (06,4150) ((KDUM(K,J),J=1,2),K=1,NOBS)
!      include 'c_obsp.inc'
      DO 150 K=1,NOBS
      N=NLY*(KDUM(K,2)-1)+KDUM(K,1)
      IJOBS(K)=N
  150 continue
      END IF
      IF (F9P) THEN
      READ(05,*)NMB9
      if (nmb9.lt.0) then
       nmb9 = -nmb9
       o9p = .true.
      end if
      if (nmb9.gt.99) nmb9 = 99
      READ(05,*) (MB9(K),K=1,NMB9)
      WRITE(06,4160) (MB9(K),K=1,NMB9)
      END IF
      PLTIM(NPLT+1)=TMAX+TMAX
      WRITE (14,4002) NLY,NXR 
      WRITE (15,4002) NLY,NXR
      WRITE (16,4002) NLY,NXR
      WRITE (17,4002) NLY,NXR
      WRITE (18,4002) NLY,NXR
      WRITE (19,4002) NLY,NXR
      IF(RAD) THEN
      WRITE(06,4050)
      ELSE
      WRITE (06,4040)
      END IF
      IF(TRANS) THEN
      WRITE(06,4240)
      IF(CIS) THEN
      WRITE(6,4200)
      ELSE
      WRITE(6,4210)
      END IF
      IF(CIT) THEN
      WRITE(6,4220)
      ELSE
      WRITE(6,4230)
      END IF
      END IF
      IF(F11P) then
       if (o13p) then
        if(trans) then
          if(heat.AND.solute)then
            WRITE (11,4033) TITL,TUNIT,ZUNIT,ZUNIT,ZUNIT,ZUNIT, &
            (COMPNAME(M),M=1,Nsol)
          else if(heat.AND.(.NOT.solute))then
            WRITE (11,4034) TITL,TUNIT,ZUNIT,ZUNIT,ZUNIT,ZUNIT
          else  
          WRITE (11,4035) TITL,TUNIT,ZUNIT,ZUNIT,ZUNIT,ZUNIT, &
          (COMPNAME(M),M=1,Nsol)
         end if 
        else
         WRITE (11,4031) TITL,TUNIT,ZUNIT,ZUNIT,ZUNIT,ZUNIT
        end if
       else
        if(trans) then
         if(heat.AND.solute)then
            WRITE (11,4032) TITL,TUNIT,ZUNIT,ZUNIT,ZUNIT,ZUNIT, &
            (COMPNAME(M),M=1,Nsol)
          else if(heat.AND.(.NOT.solute))then
            WRITE (11,4036) TITL,TUNIT,ZUNIT,ZUNIT,ZUNIT,ZUNIT
          else  
          WRITE (11,4037) TITL,TUNIT,ZUNIT,ZUNIT,ZUNIT,ZUNIT,  &
          (COMPNAME(M),M=1,Nsol)
         end if 
        else
         WRITE (11,4030) TITL,TUNIT,ZUNIT,ZUNIT,ZUNIT,ZUNIT
        end if
       end if
      end if
!
!     INITIALIZE CONSTANTS
!
      ITEST=0
      ITESTS=0
      KTIM=0
      NITT=0
      NITT1=0
      NITT2=0
      NISS=0
      NISS1=0
      JFLAG=1
      KP=0
      JPLT=0
      WRITE (06,4170) 
!
!
!   READ AND WRITE INITIAL VALUES OF PRESSURE HEAD, TOTAL HEAD,
!    THETA, AND SATURATION
!-------------------------------------------------------------
!
      CALL VSREAD
      CALL VSSIP
      CALL VSSIPSOL
      IFET=0
      IFET2=0
      CALL VSOUTP
      !!@@include 'd_kdumDealloc.inc'
      if(allocated(kdum)) deallocate(kdum)
      RETURN
 4000 FORMAT(A80)
 4001 FORMAT(A15)
 4002 FORMAT(I5,I5)
 4010 FORMAT(4A4)
 4011 FORMAT(A7) 
 4012 FORMAT(A10)
 4020 FORMAT(5X,20(1H*),1X,31HDIMENSIONS TOO LARGE FOR ARRAYS,  &
      1X,20(1H*)/5X,6HNLY = ,I6,2X,6H,NXR = ,I6)
 4030 FORMAT(A80/21HMONITORING POINT FILE/2X,6HTIME,  ,A7,2X,  &
      5x,'NODE',3x,  &
       6H XR,  ,A6,3X,6H Z,    ,A6,3X,6H H,   ,A6,3X,6H  P,  ,A6,  &
      3X,6H THETA,5X,8H     SAT,5x,'      VX',5x,'      VZ' &
      5x,'      ET')
 4031 FORMAT(A80/21HMONITORING POINT FILE/7X,6HTIME,  ,A7,6X,  &
        'NODE',15x,  & 
       6H XR,  ,A6,10X,6H Z,    ,A6,10X,6H H,   ,A6,10X,6H  P,  ,A6,  &
      12X,6H THETA,12X,8H     SAT,12x,'      VX',12x,'      VZ',  &
      12x,'      ET')
 4032 FORMAT(A80/21HMONITORING POINT FILE/2X,6HTIME,  ,A7,2X,  &
      5x,'NODE',3x,  &
       6H XR,  ,A6,3X,6H Z,    ,A6,3X,6H H,   ,A6,3X,6H  P,  ,A6,  &
       3X,6H THETA,5X,8H     SAT,10x,'TEMP',5x,'      VX',5x,  &
      '      VZ', 5x,'      ET',50(1x,A10))
 4033 FORMAT(A80/21HMONITORING POINT FILE/7X,6HTIME,  ,A7,6X,  &
      'NODE',15x,  &
       6H XR,  ,A6,10X,6H Z,    ,A6,10X,6H H,   ,A6,10X,6H  P,  ,A6,  &
       12X,6H THETA,12X,8H     SAT,17x,'TEMP',12x,'      VX',12x,  &
       '      VZ',12x,'      ET',50(1x,A10))
 4034 FORMAT(A80/21HMONITORING POINT FILE/7X,6HTIME,  ,A7,6X,  &
      'NODE',15x,  &
       6H XR,  ,A6,10X,6H Z,    ,A6,10X,6H H,   ,A6,10X,6H  P,  ,A6,  &
       12X,6H THETA,12X,8H     SAT,17x,'TEMP',12x,'      VX',12x,  &
       '      VZ',12x,'      ET')   
 4035 FORMAT(A80/21HMONITORING POINT FILE/7X,6HTIME,  ,A7,6X,  &
      'NODE',15x,  &
       6H XR,  ,A6,10X,6H Z,    ,A6,10X,6H H,   ,A6,10X,6H  P,  ,A6,  &
       12X,6H THETA,12X,8H     SAT,17x,'      VX',12x,  &
       '      VZ',12x,'      ET',50(1x,A10))    
 4036 FORMAT(A80/21HMONITORING POINT FILE/2X,6HTIME,  ,A7,2X,  &
      5x,'NODE',3x,  &
       6H XR,  ,A6,3X,6H Z,    ,A6,3X,6H H,   ,A6,3X,6H  P,  ,A6,  &
       3X,6H THETA,5X,8H     SAT,10x,'TEMP',5x,'      VX',5x,  &
      '      VZ', 5x,'      ET') 
 4037 FORMAT(A80/21HMONITORING POINT FILE/2X,6HTIME,  ,A7,2X,  &
      5x,'NODE',3x,  &
       6H XR,  ,A6,3X,6H Z,    ,A6,3X,6H H,   ,A6,3X,6H  P,  ,A6,  &
       3X,6H THETA,5X,8H     SAT,10x,'      VX',5x,  &
      '      VZ', 5x,'      ET',50(1x,A10))                 
 4040 FORMAT(5X,32HCOORDINATE SYSTEM IS RECTANGULAR)
 4050 FORMAT(5X,27HCOORDINATE SYSTEM IS RADIAL)
 4060 FORMAT(35X,60('+')/35X,'+',26X,7H VS2DRT,25X,'+'/35X,  &
     '+',23x,' VERSION 1.1',23x,'+'/35x,  &
     '+',11X,'SIMULATION OF 2-DIMENSIONAL VARIABLY',11X,'+'/  &
     35X,'+',12X,'SATURATED REACTIVE TRANSPORT',18X,'+'  &
     /35X,'+',11X,'        THROUGH POROUS MEDIA.       ',11X,'+'  &
      /35X,60('+')//)
 4070 FORMAT(//,1X,100(1H*)/5X,A80/1X,100(1H*)//10X,  &
      24HSPACE AND TIME CONSTANTS/10X,23(1H-)/  &
      5X,26HMAXIMUM SIMULATION TIME = ,E14.6,1X,A4/  &
      5X,'STARTING TIME = ',F10.4,/  &
      5X,28HNUMBER OF RECHARGE PERIODS =,I10/ &
      4X,32H MAXIMUM NUMBER OF TIME STEPS = ,I10/  &
      5X,17HNUMBER OF ROWS = ,I6/5X,20HNUMBER OF COLUMNS = ,I6)
 4080 FORMAT(5X,'AXES TILTED BY ANGLE = ',F8.2)
 4090 FORMAT(1X,'ANGLE OF AXES TILTING MUST BE BETWEEN -90 AND 90 ',  &
      'DEGREES',/,1X,'SIMULATION TERMINATED')
 4100 FORMAT(10X,16HSOLUTION OPTIONS/10X,16(1H-)/ &
      5X,'WRITE ALL PRESSURE HEADS TO FILE 8',  &
      23H AT OBSERVATION TIMES? ,L1,/  &
      5X,'STOP SOLUTION IF MAXIMUM NO.',  &
      ' OF ITERATIONS EXCEEDED IN ANY TIME STEP? ',L1/5X,  &
      'WRITE BOUNDARY FLUXES TO FILE 7? ',  &
      L1/5X,'WRITE RESULTS AT SELECTED OBSERVATION POINTS TO ',  &
      'FILE 11? ', L1/,5X,'WRITE MASS BALANCE RATES TO FILE 9? ',L1/ &
      5X,'WRITE MASS BALANCE RATES TO FILE 6? ',L1)
 4110 FORMAT(1H ,4X,35HWRITE MOISTURE CONTENTS TO FILE 6? ,L1/ &
       5X,29HWRITE SATURATIONS TO FILE 6? ,L1/ &
       5X,32HWRITE PRESSURE HEADS TO FILE 6? ,L1/  &
       5X,29HWRITE TOTAL HEADS TO FILE 6? ,L1/  &
       5X,'WRITE VELOCITIES TO FILE 6? ',L1)
 4120 FORMAT(50X,39HGRID SPACING IN VERTICAL DIRECTION, IN ,A4/ &
     (10(F10.3)))
 4130 FORMAT(50X,47HGRID SPACING IN HORIZONTAL OR RADIAL DIRECTION,  &
      ,3H IN,1X,A4/(10F10.3))
 4140 FORMAT(5X,43HTIMES AT WHICH H WILL BE WRITTEN TO FILE 08 &
      /10(5X,10E12.5,/))
 4150 FORMAT(5X,37HROW AND COLUMN OF OBSERVATION POINTS:/ &
      10(2X,2I5))
 4160 FORMAT(5X,'MASS BALANCE COMPONENTS WRITTEN TO FILE 9',  &
      /,5X,24I4)
 4170 FORMAT(5X,36HMATRIX EQUATIONS TO BE SOLVED BY SIP)
 4180 FORMAT(5X,100(1H*)/5X,17HEND OF SIMULATION/ &
        5X,100(1H*))
 4190 FORMAT(5X,'TOTAL NUMBER OF ITERATIONS FOR FLOW EQUATION = ',I6  &
      /5X,'TOTAL NUMBER OF ITERATIONS FOR TRANSPORT EQUATION = ',I6)
 4200 FORMAT(5X,'CENTRAL DIFFERENCING IN SPACE USED FOR TRANSPORT',  &
     ' EQUATION')
 4210 FORMAT(4X,' BACKWARD DIFFERENCING IN SPACE USED FOR TRANSPORT',  &
     ' EQUATION')
 4220 FORMAT(4X,' CENTRAL DIFFERENCING IN TIME USED FOR TRANSPORT',  &
     ' EQUATION')
 4230 FORMAT(4X,' BACKWARD DIFFERENCING IN TIME USED FOR TRANSPORT',  &
     ' EQUATION')
 4240 FORMAT(4X,' TRANSPORT TO BE SIMULATED')
 4250 FORMAT(4X,' NONLINEAR SORPTION TO BE SIMULATED')
      END
      SUBROUTINE STEP(JSTP)
!*** THIS IS THE SECOND HALF OF THE ORIGINAL MAIN CODE. THIS
!*** PERFORMS A SINGLE TIME STEP. THE LOOPING IS DONE IN THE CALLING
! *** PROGRAM. THE SUBROUTINE RETURNS THE SIMULATION TIME, TIME STEP,
! *** AND THE FLAG JSTP. WHEN JSTP EQUALS 1, THIS SIGNIFIES
! *** END OF SIMULATION.
      use rspac
      use kcon
      use mprop
      use press
      use disch
      use hcon
      use equat
      use jtxx
      use dumm
      use ptet
      use trxx
      use trxy1
      use plott
      use spfc
      use rpropsh
      use scon
      use equats
      use trxy2
      use trxxh
      use trxv
      use temp
      use tempcc   
      use pricon
      use coordin
      use solindex
      use phreecc
      use react
      use SCON
      USE vs2dt_rm
      USE PhreeqcRM   
      IMPLICIT DOUBLE PRECISION (A-H,P-Z)

      common/conversion/CNVTM,CNVTMI 
      COMMON/ISPAC/NLY,NLYY,NXR,NXRR,NNODES,Nsol,Nodesol
      COMMON/PND/POND
      COMMON/WGT/WUS,WDS
      COMMON/SCN1/TMPX,TMLT,DLTMX,DLTMIN,TRED
      COMMON/TCON/STIM,DSMAX,KTIM,NIT,NIT1,KP,NIT3
      COMMON/JCON/JSTOP,JFLAG,jflag1
      LOGICAL TRANS,TRANS1,TRANS2,SSTATE
      COMMON/TRXY/EPS1,EPS2,EPS3,TRANS,TRANS1,TRANS2,SSTATE,MB9(99),NMB9
      LOGICAL RAD,BCIT,ETSIM,SEEP,ITSTOP,CIS,CIT,GRAV
      LOGICAL F7P,F11P,F8P,F9P,F6P,PRNT,o9p,o11p,o12p,o13p, &
      F14P,F15P,F16P,F17P,F18P,F19P
      LOGICAL THPT,SPNT,PPNT,HPNT,VPNT
      COMMON/LOG1/RAD,BCIT,ETSIM,SEEP,ITSTOP,CIS,CIT,GRAV
      COMMON/LOG2/F7P,F11P,F8P,F9P,F6P,PRNT,o9p,o11p,o12p,o13p, &
      F14P,F15P,F16P,F17P,F18P,F19P
      COMMON/LOG4/THPT,SPNT,PPNT,HPNT,VPNT
      CHARACTER*80 TITL,filen,f5,f6,f7,f8,f9,f10,f11
      CHARACTER*6 ZUNIT,CUNX,HUNX
      CHARACTER*7 TUNIT
      COMMON/SCHAR/TITL,ZUNIT,TUNIT,CUNX,HUNX
      integer hydraulicFunctionType
      common/functiontype/ hydraulicFunctionType      
      COMMON/TTT/ IFET,IFET1,NITT,NITT1,NITT2
      LOGICAL HEAT,SOLUTE,FLOW
      COMMON/TRANSTYPE/HEAT,SOLUTE
      COMMON/TCON1/NIS,NIS1,NIS3
      COMMON/TTT1/NISS,NISS1,NISS2
      COMMON/FLO/FLOW
      COMMON/SCON1/ITESTS
      character(100) msg
      
!
! -------------------------------------------------------------
!       START OF TIME LOOP
! -------------------------------------------------------------
!
160   IF(JFLAG.EQ.1)IFET1=1
      IF (JSTOP.GT.1) THEN
         JSTP=JSTOP
         RETURN
      ENDIF
      CALL VSTMER
!
! *** IF NO MORE PERIODS TO SIMULATE, JSTOP IS SET TO 1 IN VSTMER,
! *** WE JUST RETURN AND LET THE CALLING PROGRAM TERMINATE THE
!*** THE EXECUTION
      IF (JSTOP.GT.1) THEN
         JSTP=JSTOP
         RETURN
      ENDIF
!
       TRANS1=.FALSE.
!     IF(.NOT.SSTATE) THEN
!
!   SET UP AND SOLVE MATRIX EQUATIONS FOR FLOW
!
       NIT3=0
       TRANS2=.FALSE.
 170   TRANS1=.FALSE.
!
!   SET UP AND SOLVE MATRIX EQUATIONS FOR FLOW
!
      if(nit3.gt.100) then
	  jstop = 11
	  jstp = jstop
	  return
	  end if
      nit=0
      CALL VSMGEN
      IF (JSTOP.GT.1) THEN
         JSTP=JSTOP
         RETURN
      ENDIF
!
!   CHECK FOR PONDING DURING THIS TIME STEP
!
      CALL VSPOND(IFET,IFET1,IFET2)
!
!   IF PONDING HAS OCCURRED, EQUATIONS NEED TO BE SOLVED AGAIN
!
      IF(IFET.NE.0) THEN
      IF(NIT.LT.ITMAX) THEN
      DO 50 II=1,NNODES
      IF(NTYP(II).NE.1.AND.HX(II).GT.0.0D0) P(II)=PXXX(II)
   50 CONTINUE
      nit = 1
      GO TO 170
      ELSE
      WRITE(6,4260)
      END IF
      END IF
!
!   REEVALUATE NONLINEAR COEFFICIENTS
!
      CALL VSCOEF
      NITT=NITT+NIT
!     END IF
!      IF((TRANS.OR.VPNT).AND..NOT.SSTATE) CALL VTVELO
      IF(TRANS.OR.VPNT) CALL VTVELO
!
!  Heat transport
!        
      IF(HEAT) THEN
!      IF(.NOT.SSTATE) THEN
!
!   DETERMINE VELOCITIES AND DISPERSION TENSOR
!
      CALL VTDCOEF
!      END IF
      TRANS1=.TRUE.
!
!   SET UP AND SOLVE MATRIX EQUATION FOR TRANSPORT
!
      CALL VTSETUP
      NITT1=NITT1+NIT1
      DMAX1=0.0D0
      NIT3=NIT3+1
      IF(NIT3.LT.2.OR.RHOMAX.GT.EPS2) GO TO 170
      DO 190 N=1,NNODES
      RHOOLD(N)=RHO(N)
 190  CONTINUE
      NITT2=NITT2+NIT3
      END IF
     
!
! Reactive solute transport      
!      
      IF(SOLUTE) THEN
!     
!      IF(.NOT.SSTATE) THEN
!
!   DETERMINE VELOCITIES AND DISPERSION TENSOR
!
      CALL VTDCOEFSOL
! 
!     END IF
      TRANS2=.TRUE.
     
!
!   SET UP AND SOLVE MATRIX EQUATION FOR TRANSPORT
!
      CALL VTSETUPSOL

!      NISS=NISS+ NIS1
!
!   PRINT RESULTS AND COMPUTE MASS BALANCE COMPONENTS
!
      DO 202 I=1, NNODES
      DO 201 J=1, Nsol
!      K=Nsol*(I-1)+J
!      phreeC(K)=CC(J,I)
      CCBR(J,I)=CC(J,I)
  201 CONTINUE
  202 CONTINUE
!      write(*,*)'beforereactionnnnnnnnnnnnnnnnnnn'
!      CALL VSOUTS(1,CC)
      do 161 J=1,NLY
      do 150 N=1,NXR
        IN=NLY*(N-1)+1
        if(hydraulicFunctionType.eq.0)then
          THETA(IN)=VSTHUBC(P(IN),JTEX(IN))
            else if(hydraulicFunctionType.eq.1)then
               THETA(IN)=VSTHUVG(P(IN),JTEX(IN))
              else if(hydraulicFunctionType.eq.2)then
                  THETA(IN)=VSTHUHK(P(IN),JTEX(IN))
                    else if(hydraulicFunctionType.eq.4)then
                      THETA(IN)=VSTHUOT(P(IN),JTEX(IN))
                  end if
  150 CONTINUE
  161 CONTINUE 
      iprrestartflag = 0 
      istopmsg = 0
      !#if (HEAT.AND.SOLUTE)THEN
      !#CALL EQUILIBRATEWHEAT( cc,hx,tt,NNODES,heat,nprconc,xnode,znode,  &
      !#tper,delt,npscrn,cnvtmi,nprchem,nprchxz,ipout,istopmsg,  &
      !#theta,iprrestartflag)
      !#ELSE if((.not.heat).and.solute)then
      !#call EQUILIBRATE( cc,hx,NNODES,nprconc,xnode,znode,  &
      !#tper,delt,npscrn,cnvtmi,nprchem,nprchxz,ipout,istopmsg,  &
      !#theta,iprrestartflag)  
      !#END IF
      IF (SOLUTE) THEN
          call SetConcentrationsRM(cc)
          IF (HEAT) THEN
              status = RM_SetTemperature(rm_id, tt)
          endif
          status = RM_SetTime(rm_id, stim)
          status = RM_SetTimeStep(rm_id, delt)
          status = RM_SetTimeConversion(rm_id, cnvtmi)
          status = RM_SetPrintChemistryMask(rm_id, nprchem)
          status = RM_SetPrintChemistryOn(rm_id, ipout, ipout, ipout)
          DO J=2,NLYY
              DO N=2,NXRR
                  IN=NLY*(N-1)+J
                  SATUR(IN) = 0.0d0
                  IF(POROSITY(IN).GT.0.0D0) THEN
                      SATUR(IN)=THETA(IN)/POROSITY(IN)
                  END IF
              enddo
          enddo
          status = RM_SetSaturation(rm_id, satur)
          !if (npscrn .ne. 0) then
              write(msg,"(A,F12.2)") "Chemistry at time: ", stim
              status = RM_ScreenMessage(rm_id, msg)
          !endif
          status = RM_RunCells(rm_id)
          call GetConcentrationsRM(cc)
          !call FH_WriteFiles(rm_id, ihdf, imedia, ixyz, nprchxz, iprrestartflag) 
          call FH_WriteFiles(rm_id, 0, 0, 1, nprchxz, iprrestartflag)
      END IF      
      if (solute) then
          if (heat) then
          endif
      endif
!      write(*,*)'after...reactionnnnnnnnnnnnnnnnnnn'
!      CALL VSOUTS(1,CC)
      DO 204 I=1, NNODES
      DO 203 J=1, Nsol
      K=Nsol*(I-1)+J
      CCAR(J,I)=CC(J,I)
 203  CONTINUE
 204  CONTINUE
      END IF
!
!   PRINT RESULTS AND COMPUTE MASS BALANCE COMPONENTS
!
      CALL VSOUTP
      CALL VSFLUX
!     IF(JSTOP.NE.1) GO TO 160
!
!-------------------------------------------------------------------
!     END OF TIME LOOP
!-------------------------------------------------------------------
!
! *** ASSIGN VALUES TO SUBROUTINE ARGUMENTS TO RETURN
      JSTP = JSTOP
      RETURN
 4260 FORMAT(5X,'-- WARNING --  INFILTRATION/PONDING BOUNDARY WAS NOT',  &
      ' SOLVED ACCURATELY FOR THIS TIME STEP')
      END
    
      SUBROUTINE VSREAD
!******
!VSREAD
!******
!
!   PURPOSE: TO READ INITIAL HEAD AND SATURATION DATA
!
! ----------------------------------------------------------------
!
!   SPECIFICATIONS FOR ARRAYS AND SCALARS
!
      use rspac
      use kcon
      use mprop
      use press
      use jtxx
      use dumm
      use ptet
      use trxx
      use idumm
      use rpropsh
      use scon
      use equat
      use BF
      use equats
      use trxy2
      use trxxh
      use trxv
      use temp
      use coordin
      use solindex
      use phreecc
      use compnam
      use itemblo
      use itemtxb
      use react
      USE vs2dt_rm
      USE PhreeqcRM
      USE PRICON
      use SCON
      IMPLICIT DOUBLE PRECISION (A-H,P-Z)
      
      common/conversion/CNVTM,CNVTMI 
      COMMON/ISPAC/NLY,NLYY,NXR,NXRR,NNODES,Nsol,Nodesol
      COMMON/WGT/WUS,WDS
      COMMON/JCON/JSTOP,JFLAG,jflag1
      COMMON/TCON/STIM,DSMAX,KTIM,NIT,NIT1,KP,NIT3
      LOGICAL TRANS,TRANS1,TRANS2,SSTATE
      COMMON/TRXY/EPS1,EPS2,EPS3,TRANS,TRANS1,TRANS2,SSTATE,MB9(99),NMB9
      LOGICAL PHRD
      LOGICAL RAD,BCIT,ETSIM,SEEP,ITSTOP,CIS,CIT,GRAV
      COMMON/LOG1/RAD,BCIT,ETSIM,SEEP,ITSTOP,CIS,CIT,GRAV
      LOGICAL F7P,F11P,F8P,F9P,F6P,PRNT,o9p,o11p,o12p,o13p, &
      F14P,F15P,F16P,F17P,F18P,F19P
      COMMON/LOG2/F7P,F11P,F8P,F9P,F6P,PRNT,o9p,o11p,o12p,o13p, &
      F14P,F15P,F16P,F17P,F18P,F19P
      COMMON/hinterp/ DELPP,nprop,I1,I2,I3,I4,I5,I6
      CHARACTER*80 TITL
      CHARACTER*80 IFMT,FREE,UNFORMATTED
      CHARACTER*6 ZUNIT,CUNX,HUNX
      CHARACTER*7 TUNIT      
      COMMON/SCHAR/TITL,ZUNIT,TUNIT,CUNX,HUNX
      integer hydraulicFunctionType,iuTemperature,iuHead,iuConcentration
      common/functiontype/ hydraulicFunctionType
!      COMMON/VERSION/VER2P5
!     LOGICAL VER2P5
      common/iuNumber/ iuHead, iuConcentration,iuTemperature
      LOGICAL HEAT,SOLUTE,FLOW
      COMMON/TRANSTYPE/HEAT,SOLUTE
      integer NHTPROP,NSTPROP
      COMMON/TRANNSPROP/NHTPROP,NSTPROP
      COMMON/FLO/FLOW
!      LOGICAL VER1P0
!      COMMON/VERSION/VER1P0   
      !DIMENSION Solcomp(50)
      common/solind/ INSOL1(7),INSOL2(7),Solcomp(50)
      logical axes(2) 
      common/axis/axes
      common/ITEMK/KNLY,KNXR,KNNODE
      !!@@include 'd_idummAlloc.inc'
      allocate(IDUM(NXR))
      !!@@include 'd_itembloAlloc.inc'
      allocate(ITEMBL(KNNODE),ITBDUM(KNXR))
      !!@@include 'd_itemtxbAlloc.inc'
      allocate(ITEMTX(KNNODE),ITDUM(KNXR))
      
!-----------------------------------------------------------------------
!
!   READ AND WRITE INITIAL DATA FOR SIMULATION
!
      FREE = 'free'
      UNFORMATTED = 'unformatted'
!
!     modified for reactive transport
!     
      READ(5,*) EPS,HMAX,WUS
      EPS1=0.0D0
      EPS2=0.0D0
      EPS3=0.0D0
      IF(HEAT)READ(5,*)EPS1,EPS2
      IF(SOLUTE)READ(5,*)EPS3
      READ (5,*) MINIT,ITMAX
      READ (05,*) PHRD
      READ (05,*) NTEX,NPROP
      READ (05,*) hydraulicFunctionType
!      READ (05,*) iuTemperature
      NHTPROP = 0
      NSTPROP = 0
      IF(HEAT) NHTPROP=6
      IF(SOLUTE) NSTPROP=3
!
!  revision for Rossi-Nimmo
!
      if (hydraulicFunctionType.eq.4) nprop = 19
      !!@@include 'd_rpropshAlloc.inc'
      allocate(HK(NTEX,NPROP))
      allocate(HT(NTEX,6))
      allocate(HS(NTEX,3))
      allocate(ANIZ(NTEX))      
      if (hydraulicFunctionType.eq.4) nprop = 6
!
!  end revision
!
!
!   CHECK THAT SUM OF WEIGHTING FACTORS IS EQUAL TO ONE
!
      WRITE (6,4000) EPS,ZUNIT,EPS1,EPS2,EPS3,HMAX
      IF(WUS.EQ.1.0D0) THEN
      WDS=0.0D0
      WRITE(06,4020)
      ELSE
      IF(WUS.EQ.0.5D0) THEN
      WDS=0.5D0
      WRITE(06,4070)
      ELSE
      WUS=0.0D0
      WRITE(06,4010)
      END IF
      END IF
      WRITE (6,4080) NTEX,NPROP,NHTPROP,NSTPROP,MINIT,ITMAX
      !!@@include 'd_sconAlloc.inc'
      allocate (DHMX(ITMAX+1))
!      include 'c_sconItmax
      WRITE (06,4100)
      IF (HEAT) WRITE(06,4110)
      IF (SOLUTE) WRITE(06,4111)
!
!   READ AND WRITE MATERIAL PROPERTIES FOR EACH TEXTURAL CLASS
!

      DO 21 J22=1,NTEX
      DO 10 J23=1,NPROP
   10 HK(J22,J23)=0.0D0
      DO 20 J23=1,NHTPROP
   20 HT(J22,J23)=0.0D0
      DO 21 J23=1,NSTPROP
   21 HS(J22,J23)=0.0D0
      
      DO 30 J22=1,NTEX
      READ (5,*) J
      READ (5,*) ANIZ(J),(HK(J,I),I=1,NPROP)
      WRITE (6,4120) J,ANIZ(J),(HK(J,I),I=1,NPROP)
      IF(HEAT) THEN
!
!  modification to read for heat transport 
!
      read(5,*) (HT(j,I),I=1,6)
      write(6,4130) (HT(j,I),I=1,6)
      HT(J,3)=HT(J,3)*(1.-HK(J,3))
      END IF
      IF(SOLUTE) THEN
!
!  modification to read for solute transport
!
      read(5,*) (HS(j,I),I=1,3)
      write(6,4130)(HS(j,I),I=1,3)
      END IF
!
!  revsion for Rossi-Nimmo
!
      if(j.ne.1) then
      if (hydraulicFunctionType.eq.4) then
       hk(j,7) = hk(j,4)*(2.0D0/(2.0D0+hk(j,6)))**(-1.0D0/hk(j,6))
       hk(j,8) = .50D0*hk(j,6)*(2.0D0/(2.0D0+hk(j,6)))**((2.0D0+hk(j,6)/hk(j,6)))
       hk(j,9) =  hk(j,6)*exp(1.0D0)*(hk(j,4)/hk(j,5))**hk(j,6)
       hk(j,10) = hk(j,5)*exp(-1.0D0/hk(j,6))
       hk(j,11) = VSTHUOT(-hk(j,7),j)
       hk(j,12) = VSTHUOT(-hk(j,10),j)
       hk(j,14) = (hk(j,6) + 1.0D0)/hk(j,6)
       hk(j,15) = (hk(j,12)/hk(j,3))**hk(j,14)
       hk(j,16) = 2.0D0*(hk(j,8))**(.50D0)/hk(j,4)
       hk(j,17) = (1.0D0 - hk(j,11)/hk(j,3))**(0.50D0)
       hk(j,18) = hk(j,9)*(exp(hk(j,12)/(hk(j,9)*hk(j,3)))-1.0D0)/hk(j,5)
       hk(j,19) = hk(j,18)+((hk(j,11)/hk(j,3))**hk(j,14)-hk(j,15))/(hk(j,4)*hk(j,14))
       hk(j,13) = hk(j,19) + hk(j,16)*hk(j,17)
       hk(j,13) = hk(j,13)*hk(j,13)  
!      pt = 0.0D0

      end if
      end if
!
!  end revisions
!
 30    CONTINUE

!     convert alpha parameter if reading version 2.5 data set
!      IF (VER2P5.AND.(hydraulicFunctionType.EQ.1)) THEN
!         DO 31 J=1,NTEX
!            IF (HK(J,4).NE.0) THEN
!               HK(J,4) = -1.D0/HK(J,4)  
!            END IF
!   31    CONTINUE
!     ENDIF
      WRITE (06,4140)
!
!    READ TEXTURAL CLASS INDEX MAP
!
      READ (05,*) IROW
      IF(IROW.EQ.0) THEN
!      DO 54 K=1,NNODES
!        JTEX(K)=1
!        J22=JTEX(K)
!        HX(K)=HK(J22,1)
!  54  CONTINUE        
!      WRITE(06,4090)
!      DO 51 J=1,KNLY
!      READ (05,*)(ITBDUM(N),N=1,KNXR)
!      DO 41 N=1,KNXR
!      IN=KNLY*(N-1)+J
!      I22=ITBDUM(N)
!  41  ITEMBL(IN)=I22
!  51  CONTINUE 
!      DO 52 J=1,KNLY
!      READ (05,*) (ITDUM(N),N=1,KNXR)
!      DO 42 N=1,KNXR
!      IN=KNLY*(N-1)+J
!      NI=NLY*N+J+1
!      NTEMBX=ITDUM(N)
!      ITEMTX(IN)=NTEMBX
!      if(ITEMBL(IN).EQ.0)ITEMTX(IN)=1
!      ITBDUM(N)=ITEMTX(IN) 
!      ITEMTX(IN)=ITBDUM(N)
!      JTEX(NI)=ITEMTX(IN)
!      J22=JTEX(NI)
!      HX(NI)=HK(J22,1)
!  42  CONTINUE
!  52  CONTINUE
  
!      DO 55 J=1,NLY
!      DO 45 N=1,NXR
!      IN=NLY*(N-1)+J
!      IDUM(N)=JTEX(IN)
!  45  CONTINUE
!      if (ntex.gt.9) then
!       write (06,4151) j,(idum(n),n=1,nxr)
!      else
!       WRITE (06,4150) J,(IDUM(N),N=1,NXR)
!      end if
!  55 CONTINUE      
!      ELSE
!Uncoment the next lines until the else statement located below label 50 contiune statement line
! and remove or coment the lines between if you are not using inputfile generated by Argus ONE GUI
     WRITE(06,4090)
     DO 50 J=1,NLY
     READ (05,*) (IDUM(N),N=1,NXR)
      if (ntex.gt.9) then
      write (06,4151) j,(idum(n),n=1,nxr)
      else
       WRITE (06,4150) J,(IDUM(N),N=1,NXR)
      end if
     DO 40 N=1,NXR
     IN=NLY*(N-1)+J
      J22=IDUM(N)
      HX(IN)=HK(J22,1)
  40 JTEX(IN)=J22
  50 CONTINUE
     ELSE
!
!    READ TEXTURE CLASSES BY BLOCK--EITHER CONTINUOUS LAYERS OR
!    LAYERS BOUNDED BY VERTICAL DISCONTINUITIES.
!
      WRITE (06,4040)
      JTP=1
   60 READ (05,*) IL,IR,JBT,JRD
      DO 70 N=IL,IR
      IDUM(N)=JRD
   70 CONTINUE
      IF(IR.LT.NXR) GO TO 60
      DO 80 J=JTP,JBT
      if (ntex.gt.9) then
       write (06,4151) j,(idum(n),n=1,nxr)
      else
       WRITE (06,4150) J,(IDUM(N),N=1,NXR)
      end if
   80 continue
      DO 90 J=JTP,JBT
      DO 90 N=1,NXR
      IN=NLY*(N-1)+J
      J22=IDUM(N)
      HX(IN)=HK(J22,1)
      JTEX(IN)=J22
   90 CONTINUE
      IF(JBT.EQ.NLY) GO TO 100
      JTP=JBT+1
      GO TO 60
      END IF
  100 CONTINUE
!
!   BORDERS OF DOMAIN ARE ALL SET TO NO FLOW BOUNDARIES
!
      DO 110 I=1,NLY
      I1=NNODES-I+1
      HX(I)=0.0D0
  110 HX(I1)=0.0D0
      DO 120 I=2,NXR
      I1=(I-1)*NLY
      HX(I1)=0.0D0
  120 HX(I1+1)=0.0D0
!
!   READ INITIAL HEADS OR MOISTURE CONTENTS
!
      READ (05,*) IREAD,FACTOR
      IF(IREAD.EQ.2) THEN
      READ (05,*) DWTX,HMIN
      WRITE (06,4190) DWTX,ZUNIT,HMIN,ZUNIT,DWTX,ZUNIT
!
!  CALCULATE EQUILIBRIUM INITIAL HEAD PROFILE
!
      DO 130 J=2,NLYY
      DO 130 N=2,NXRR
      IN=NLY*(N-1)+J
      IF(HX(IN).EQ.0.0D0) GO TO 130
      IF(CS1.EQ.1.0D0) THEN
      Z1=DZZ(J)
      ELSE
      Z1=DZZ(J)*CS1+RX(N)*CS2
      END IF
      P1=Z1-DWTX
      IF(P1.LT.HMIN)P1=HMIN
      P(IN)=P1-Z1
      PXXX(IN)=P(IN)
  130 CONTINUE
      ELSE
      IF(IREAD.EQ.0) THEN
      WRITE (6,4170) FACTOR
      ELSE 
      IF(IREAD.EQ.1)READ(05,*)IU,IFMT
      END IF
!      if(IFMT.eq.UNFORMATTED) then
      if(iread.eq.3) then
       stimStart = -1.d0
       write (6,4181) stim, TUNIT
       if (trans) then
       do 
        read (13,err = 131, end = 132) stimStart, p, cc
        if (stimStart.ge.stim) EXIT
       end do
       else
        do
         read (13,err = 131, end = 132) stimStart, p
         if (stimStart.ge.stim) EXIT
        end do
       end if
 132   continue
       if (stimStart.ne.stim) then
        write (6,4183) stim, TUNIT, stimStart, TUNIT
        stim = stimStart
       end if
       go to 133
 131   write (6,4182)
       jstop = 11
       return
      else
      WRITE (06,4180) IU,FACTOR
       
      DO 160 J=1,NLY
      do I=1,NXR
        DUM(I)=0.0D0
      END DO   
      IF(IREAD.EQ.1) then
      IF(IFMT.eq.FREE) THEN
!
!   READ INITIAL CONDITIONS FROM FILE IU
!
      read (iu,*) (dum(n),n=1,nxr)
      ELSE
!      READ (iuHead,FMT=IFMT) (DUM(N),N=1,NXR)
      READ (IU,FMT=IFMT) (DUM(N),N=1,NXR)
      end if
      else
      DO 140 N=1,NXR
  140 DUM(N)=FACTOR
      end if
      DO 150 N=1,NXR
      IN=NLY*(N-1)+J
      IF(IREAD.ne.0)DUM(N)=DUM(N)*FACTOR
      IF(CS1.EQ.1.0D0) THEN
      Z1=DZZ(J)
      ELSE
      Z1=DZZ(J)*CS1+RX(N)*CS2
      END IF
      IF(.NOT.PHRD) THEN
      IF(DUM(N).LE.0.0D0) THEN
      WRITE(6,4230) J,N
      jstop=4
      return
      END IF
!
!   CONVERT INITIAL MOISTURE CONTENTS TO HEADS
!
      if(hydraulicFunctionType.eq.1) then
       P(IN)=VSTHNVVG(DUM(N),JTEX(IN))-Z1
      else
       if(hydraulicFunctionType.eq.2) then
        P(IN)=VSTHNVHK(DUM(N),JTEX(IN))-Z1
       else
        if(hydraulicFunctionType.eq.0) then
         P(IN)=VSTHNVBC(DUM(N),JTEX(IN))-Z1
        else
         if(hydraulicFunctionType.eq.3) then
          P(IN)=VSTHNVTAB(DUM(N),JTEX(IN))-Z1
         else
          P(IN)=VSTHNVOT(DUM(N),JTEX(IN))-Z1
         end if
        end if
       end if
      end if
      THETA(IN)=DUM(N)
      ELSE
      P(IN)=DUM(N)-Z1
      END IF
      PXXX(IN)=P(IN)
  150 CONTINUE
  160 CONTINUE
      end if
      if(jstop.gt.1) return
!
!   COMPUTE INITIAL NONLINEAR COEFFICIENT VALUES
!
      END IF
      
 133  CALL VSCOEF
!
!   IF ET IS TO BE SIMULATED, ALL VARIABLES MUST BE ENTERED HERE.
!
      READ(05,*) BCIT,ETSIM
      IF(BCIT .OR. ETSIM) THEN
!
!   COMPUTE DEPTHS FOR ET CALCULATIONS
!
      DPTH(1)=-0.5D0 *DELZ(1)
      DO 170 J=2,NLYY
      DO 170 N=2,NXRR
      IN=NLY*(N-1)+J
      JM1=IN-1
      IF(HX(IN).NE.0.0D0) THEN
      IF(HX(JM1).EQ.0.0D0) THEN
      DPTH(IN)=0.0D0
      ELSE
      DPTH(IN)=DPTH(JM1)+DELZ(J-1)
      END IF
      END IF
  170 CONTINUE
      WRITE (6,4200)
      CALL VSOUT(2,DPTH)
!
!   READ EVAPORATION VARIABLES
!
      READ(05,*)NPV,ETCYC
      npv1 = npv
      if(npv.lt.0) npv = -npv
      !!@@include 'd_ptetAlloc.inc'
      allocate(PEVAL(NPV))
      allocate(PTVAL(NPV))
      allocate(RDC(6,NPV))
      DO 713 I=1,NPV
      PEVAL(I) = 0.0D0
      PTVAL(I) = 0.0D0
      DO 714 J=1,6
      RDC(J,I) = 0.0D0
 714  CONTINUE
 713  CONTINUE
      WRITE(6,4030) NPV,ETCYC,TUNIT
      IF(BCIT) THEN
      READ (05,*)(PEVAL(I),I=1,NPV)
      READ(05,*)(RDC(1,I),I=1,NPV)
      READ(05,*)(RDC(2,I),I=1,NPV)
      WRITE (06,4050)ZUNIT,TUNIT,ZUNIT,ZUNIT,(I,PEVAL(I),RDC(1,I),  &
      RDC(2,I),I=1,NPV)
      END IF
      IF (ETSIM )THEN
!
!   READ TRANSPIRATION VARIABLES
!
      READ(05,*)(PTVAL(I),I=1,NPV)
      READ(05,*) (RDC(3,I),I=1,NPV)
      READ(05,*) (RDC(4,I),I=1,NPV)
      READ(05,*) (RDC(5,I),I=1,NPV)
      READ(05,*) (RDC(6,I),I=1,NPV)
      WRITE(06,4060)ZUNIT,TUNIT,ZUNIT,ZUNIT,ZUNIT,ZUNIT,(I,PTVAL(I),  &
      (RDC(J,I),J=3,6),I=1,NPV)
      NPV = npv1
      END IF
      END IF
      DO 180 IN=1,NNODES
      NTYP(IN)=0
      IF(SOLUTE) NCTYP(IN)=0
      IF(HEAT) NHTYP(IN)=0
      IF(HX(IN).GT.0.0D0) THLST(IN)=THETA(IN)
  180 CONTINUE
!
!    READ INITIAL TEMPERATURES IF TRANSPORT EQUATION IS TO
!    BE SOLVED
!
      IF (HEAT) THEN
      READ(05,*) IREAD,FACTOR
      IF(IREAD.EQ.0) THEN
      WRITE(6,4210) FACTOR
      DO 190 N=1,NNODES
      IF(HX(N).GT.0.0D0) THEN
       TT(N) = FACTOR
       TTOLD(N)= FACTOR
      ELSE
       TT(N) = 0.0D0
       TTOLD(N)= 0.0D0
      END IF
      RHO(N)=VTRHO(TT(N),JTEX(N))
      RHOOLD(N)=RHO(N)
  190 CONTINUE
      ELSE
      READ(05,*)IU,IFMT
      if (IFMT.NE.UNFORMATTED) then
      WRITE(06,4220) IU,FACTOR
      DO 202 J=1,NLY
      if (IFMT.EQ.FREE) then
       read(iu,*) (dum(n),n=1,nxr)
      else
!       READ(iuConcentration,FMT=IFMT) (DUM(N),N=1,NXR)
       READ(iu,FMT=IFMT) (DUM(N),N=1,NXR)
      end if
       DO 202 N=1,NXR 
      IN=NLY*(N-1)+J
      IF(HX(IN).GT.0.0D0) THEN
       TT(IN)=DUM(N)*FACTOR
       TTOLD(IN)=TT(IN)
      ELSE
       TT(IN)=0.0D0
       TTOLD(IN)= 0.0D0   
      end if
      RHO(IN)=VTRHO(TT(IN),JTEX(IN))
      RHOOLD(IN)=RHO(IN) 
  202 CONTINUE   
      end if
      end if
      else
      do 210 n = 1,nnodes    
      RHO(N)=VTRHO(TT(N),JTEX(N))
      RHOOLD(N)=RHO(N)
  210 CONTINUE
      END IF
!
!    READ INITIAL MULTI-SOLUTE CONCENTRATION IF SOLUTE TRANSPORT EQUATION IS TO
!    BE SOLVED
!      
      IF (SOLUTE) THEN
          READ(05,*) IREAD
          insol2 = -1
          indsol2 = -1
          cmixfarc = 1.0d0
          !INSOL2(1)=2
          !DO  I=1,7
          !    INSOL2(I)=-1
          !    DO J=1,NNODES
          !        INDSOL2(I,J) = INSOL2(I)
          !        CMIXFARC(I,J) = 1.0d0
          !    END DO
          !END DO  
          IF(IREAD.EQ.0) THEN
              READ(05,*)(INSOL1(I),I=1,7)
              INSOL2(1)=2
              DO 212 I=2,7
                  INSOL2(I)=-1
212           CONTINUE       
              DO 182 I=1,7
                  DO 181 J=1,NNODES
                      INDSOL1(I,J) = INSOL1(I)
                      !      INDSOL2(I,J) = INSOL2(I)
                      !      CMIXFARC(I,J) = 1.0d0
181               CONTINUE
182           CONTINUE
          ELSE if (IREAD.EQ.1)then
              DO 403 K=1,7  
                  DO 402 J=1,NLY
                      READ (05,*)(DUM(N),N=1,NXR)
                      DO 401 N=1,NXR
                          IN=NLY*(N-1)+J
                          INDSOL1(K,IN)=DUM(N)
                          !      write(*,*)"INDSOL1(",K,",",NI,")=ITEMTX(",IN,")=",INDSOL1(K,NI),ITEMTX(IN)
401                   continue
402               continue
403           continue
          END IF 
          DO 185 I=1, Nsol
              Solcomp(I)=0.0d0
185       continue  
          DO I=1, NLY
              DO J=1, NXR
                  IN=NLY*(J-1)+I  
                  if (I.eq.1.or.I.eq.NLY)then
                      INDSOL1(1,IN)=1
                  END if   
                  if (J.eq.1.or.J.eq.NXR)then
                      INDSOL1(1,IN)=1 
                  end if    
              END DO       
          END DO
          !      do 184 I=1,7
          !      do 183 J=1, NNODES  
          !     write(6,*)"INDSOL1(",I,",",J,")=",INDSOL1(I,J)
          ! 183  continue
          ! 184  continue   
          do 205 I=1, Nodesol
              phreeC(I)= 0.0d0
205       continue
          
          CALL CreateMappingRM(INDSOL1, axes, NXR, NLY) 
          ! Set porosity
          do i = 1, nnodes            
              porosity(i) = HK(jtex(i),3)
          enddo
          status = RM_SetPorosity(rm_id, porosity) 
          CALL InitializeRM(cmixfarc, indsol1, indsol2, ic1_reordered)
          CALL GetConcentrationsRM(cc)
          
          ! Set SolComp
          !status = RM_InitialPhreeqc2Concentrations(rm_id, Solcomp(1), 1, INSOL1(1))  
          do i = 1, Nsol
              WRITE(06,4012)COMPNAME(I), Solcomp(I)
          enddo  
          
          ! Set ccold
          DO 203 N=1,NXR
              DO 201 M=1,Nsol
                  IN=NLY*(N-1)+J
                  CCOLD(M,IN)=CC(M,IN)
201           CONTINUE
203       CONTINUE
          do 162 J=1,NLY
              do 156 N=1,NXR
                  IN=NLY*(N-1)+1
                  if(hydraulicFunctionType.eq.0)then
                      THETA(IN)=VSTHUBC(P(IN),JTEX(IN))
                  else if(hydraulicFunctionType.eq.1)then
                      THETA(IN)=VSTHUVG(P(IN),JTEX(IN))
                  else if(hydraulicFunctionType.eq.2)then
                      THETA(IN)=VSTHUHK(P(IN),JTEX(IN))
                  else if(hydraulicFunctionType.eq.4)then
                      THETA(IN)=VSTHUOT(P(IN),JTEX(IN))
                  end if
156           CONTINUE
162       CONTINUE 
          iprrestartflag = 0 
          istopmsg = 0

          !if (HEAT.AND.SOLUTE)THEN
              !CALL EQUILIBRATEWHEAT( cc,hx,tt,NNODES,heat,nprconc,xnode,znode,  &
              !tper,delt,npscrn,cnvtmi,nprchem,nprchxz,ipout,istopmsg,  &
              !theta,iprrestartflag)
          !ELSE IF ((.NOT.HEAT).AND.SOLUTE)THEN
              !call EQUILIBRATE( cc,hx,NNODES,nprconc,xnode,znode,  &
              !tper,delt,npscrn,cnvtmi,nprchem,nprchxz,ipout,istopmsg,  &
              !theta,iprrestartflag)   
          !ENDIF
          IF (SOLUTE) THEN
              call SetConcentrationsRM(cc)
              IF (HEAT) THEN
                  status = RM_SetTemperature(rm_id, tt)
              endif
              
              status = RM_SetTime(rm_id, 0.0d0)
              status = RM_SetTimeStep(rm_id, delt)
              status = RM_SetTimeConversion(rm_id, cnvtmi)
              status = RM_SetPrintChemistryMask(rm_id, nprchem)
              status = RM_SetPrintChemistryOn(rm_id, ipout, ipout, ipout)
              status = RM_SetSaturation(rm_id, theta)
              status = RM_RunCells(rm_id)
              call GetConcentrationsRM(cc)
              !call FH_WriteFiles(rm_id, ihdf, imedia, ixyz, nprchxz, iprrestartflag) 
              call FH_SetPointers(xnode(1), xnode(1), znode(1), ic1_reordered(1,1), theta(1), forward1(1))
              call FH_WriteFiles(rm_id, 0, 0, 1, nprchxz(1), iprrestartflag)
          END IF
      END IF
!
!   COMPUTE INTERCELL CONDUCTANCES
!   
  
      CALL VSHCMP
!
!  modifications Aug 2008 to allow output of
!   fluxes along boundary segment.  Read in
!   cells on selected boundary faces here.
!
      if (f7p) then
       read(5,*) numBF, maxnumcells
       !!@@include 'd_BFAlloc.inc'
!      if (allocated(idBF)) deallocate(idBF)
!      if (allocated(numcellsBF)) deallocate(numcellsBF)
!      if (allocated(nodenum)) deallocate(nodenum)
!      if (allocated(totalBF)) deallocate(totalBF)
!      if (allocated(currentBF)) deallocate(currentBF)
      allocate(idBF(numBF))
      allocate(numcellsBF(numBF))
      allocate(nodenum(numBF,maxnumcells))
      allocate(totalBF(numBF,2))
      allocate(currentBF(numBF,4))       
       do 250 i = 1,numBF
        read(5,*) idBF(i), numcellsBF(i)
        do 250 j = 1,numcellsBF(i)
         read (5,*) jj,nn
         nodenum(i,j) = nly*(nn-1) + jj
 250   continue
      end if
       !!@@include 'd_itembloDealloc.inc'
      if(allocated(itembl)) deallocate(ITBDUM)
	  if(allocated(itbdum)) deallocate(itbdum)
       !!@@include 'd_itemtxbDealloc.inc'
       deallocate(ITEMTX,ITDUM)
!     write(*,*)"Finshed reading initial data................................"    
      RETURN
 4000 FORMAT(10X,27HINITIAL MOISTURE PARAMETERS/10X,27(1H_)// &
     5X,'CONVERGENCE CRITERION FOR SIP FOR FLOW (EPS) =',1PE12.3,1X,A4/ &
     5X,'CONVERGENCE CRITERION FOR SIP FOR HEAT TRANSPORT (EPS1) =' ,  &
     1PE12.3,1X,/5X,'CONVERGENCE CRITERION FOR OUTER'& 
     'ITERATION (EPS2)  = ',1PE12.3,1X,/5X,'CONVERGENCE CRITERION'&  
     'FOR SIP FOR SOLUTE TRANSPORT(EPS3) =',1PE12.3,1X,/5X,  &
      23HDAMPING FACTOR,HMAX = ,1PE12.3)
! 4001 FORMAT(I1,A80)   
 4010 FORMAT(5X,46HGEOMETRIC MEAN USED FOR INTERCELL CONDUCTIVITY)
 4012 FORMAT(4X,A10,F10.6)
 4020 FORMAT(5X,50HUPSTREAM WEIGHTING USED FOR INTERCELL CONDUCTIVITY)
 4030 FORMAT(//15X,'NUMBER OF EVAPORATION AND/OR EVAPOTRASPIRATION PERIODS= ',  &
      I6,/,15X,'LENGTH OF EACH PERIOD = ',F10.4,2X,A4)
 4040 FORMAT(5X,'TEXTURAL CLASSES READ IN BY BLOCK')
 4050 FORMAT(//5X,'EVAPORATION   POTENTIAL      SURFACE   ATMOSHERIC', &
      /'       PERIOD        RATE       RESISTANCE    PRESSURE', &
      /19X,A4,'/',A4,3X,A4,'**(-1)',5X,A4,/,1X,90('-'),  &
      25(/,5X,I6,4X,3E14.5))
 4060 FORMAT(//,3X,'TRANSPIRATION   POTENTIAL         ROOT       ACTIVITY &
           ACTIVITY        ROOT', &
      /'       PERIOD        RATE            DEPTH     AT BOTTOM       A&
      T TOP       PRESSURE',/,19X,A4,'/',A4,9X,A4,5X,A4,'**(-2)',4X,A4,&
      '**(-2)',8X,A4,/,1X,90('-'),25(/,5X,I6,4X,5E14.5))
 4070 FORMAT(5X,47HARITHEMTIC MEAN USED FOR INTERCELL CONDUCTIVITY)
 4080 FORMAT(5X,34HNUMBER OF SOIL TEXTURAL CLASSES = ,I10/  &
      5X,43HNUMBER OF SOIL PARAMETERS FOR EACH CLASS = ,I10/  &
      5X,'NUMBER OF HEAT TRANSPORT PARAMETERS FOR EACH CLASS = ',I10/  &
      5X,'NUMBER OF SOLUTE TRANSPORT PARAMETERS FOR EACH CLASS = ' &
      ,I10/5X,47HMINIMUM PERMITTED NO. OF ITERATIONS/TIME STEP =,I10/  &
      5X,47HMAXIMUM PERMITTED NO. OF ITERATIONS/TIME STEP =,I10)
 4090 FORMAT(5X,41HTEXTURAL CLASS TO BE READ IN FOR EACH ROW)
 4100 FORMAT(41X,35HCONSTANTS FOR SOIL TEXTURAL CLASSES// &
      10X,10HANISOTROPY,7X,4HKSAT,5X,8HSPECIFIC,4X,8HPOROSITY,/,&
      36X,7HSTORAGE)
 4110 FORMAT(12X,'ALPHAL',8X,'ALPHAT',6X,'Cs',9X,'KT MIN',  &
      4X,' KT MAX ',4X,'   Cw   ')
 4111 FORMAT(12X,'ALPHAL',8X,'ALPHAT',6X,'DM')
 4120 FORMAT(1X,7HCLASS #,I2,/9X,3(1PD12.3),14(7(1PD12.3),/))
 4130 FORMAT(9X,10(1PD12.3))
 4140 FORMAT(6X,24HTEXTURAL CLASS INDEX MAP//   )
 4150 FORMAT(1H ,5X,I5,2X,100(99999I1))
 4151 FORMAT(1H ,5X,I5,2X,100(99999I2))
 4160 FORMAT(5X,24H ****** VALUE OF ITMAX =,I5,8HEXCEEDS , &
      44HDIMENSION OF DHMX, PROGRAM TERMINATED ******)
 4170 FORMAT(5X,48HINITIAL PRESSURE HEAD OR MOISTURE CONTENT WAS SE, &
      24HT TO A CONSTANT VALUE OF,1PE12.3)
 4180 FORMAT(5X,48HINITIAL PRESSURE HEAD OR MOISTURE CONTENT WAS RE, &
      12HAD FROM UNIT,I5, &
      20H A SCALING FACTOR OF,1PE12.3,9H WAS USED)
 4181 FORMAT(5X,'Simulation restarted at time ', E15.7,1x, a4, & 
       '.  Initial conditions imported from previous run.')
 4182 FORMAT('Error reading unformatted initial conditions.', &
       '  Simulation stopped.')
 4183 FORMAT(5x,'WARNING ---- Requested start time ', E15.7,1x, a4,  & 
      ' differs from actual start time ', E15.7,1x, a4,'.')
 4190 FORMAT(5X,'EQUILLIBRIUM PROFILE USED TO INITIALIZE PRESSURE',  &
       27H HEADS ABOVE WATER TABLE AT,F10.2,1X,A4,1X, &
       12HBELOW ORIGIN/5X, &
       57HEQUILLIBRIUM PROFILE ONLY USED UNTIL PRESSURE HEADS EQUAL, &
       F10.2,1X,A4/5X, &
       20HPRESSURE HEADS BELOW,F10.2,1X,A4,16H ARE HYDROSTATIC)
 4200 FORMAT(1H ,50X,18HDEPTH FROM SURFACE)
 4210 FORMAT('     INITIAL TEMPERATURE SET TO A CONSTANT VALUE OF ',  &
      1PE12.3)
 4215 FORMAT('    INITIAL CONCENTRATION SET TO A CONSTANT VALUE OF ',  &
      1PE12.3,' GRAM')     
 4220 FORMAT('     INITIAL TEMPERATURE WAS READ FROM UNIT',I5,  &
      ' A SCALING FACTOR OF, ',1PE12.3,' WAS USED')
 4225 FORMAT('     INITIAL CONCENTRATION WAS READ FROM UNIT',I5,  &
      ' A SCALING FACTOR OF, ',1PE12.3,' WAS USED')    
 4230 FORMAT('  INITIAL MOISTURE CONTENT AT ROW ',I3,' COLUMN ',  &
      I3,' IS LESS THAN OR EQUAL TO 0.',/'  PROGRAM TERMINATED')
      END
      SUBROUTINE VSTMER
!******
!VSTMER
!******
!
!     PURPOSE: TO CONTROL THE TIME SEQUENCE OF SIMULATION
!     AND TO READ NEW BOUNDARY CONDITION DATA
!
! ----------------------------------------------------------------
!
!   SPECIFICATIONS FOR ARRAYS AND SCALARS
!
      use rspac
      use kcon
      use mprop
      use press
      use disch
      use trxx
      use plott
      use idumm
      use spfc
      use scon
      use isdumm
      use ihdumm
      use trxxh
      use solindex
      use PhreeqcRM
      use vs2dt_rm
      IMPLICIT DOUBLE PRECISION (A-H,P-Z)

      COMMON/ISPAC/NLY,NLYY,NXR,NXRR,NNODES,Nsol,Nodesol
      COMMON/PND/POND
      COMMON/SCN1/TMPX,TMLT,DLTMX,DLTMIN,TRED
      COMMON/TCON/STIM,DSMAX,KTIM,NIT,NIT1,KP,NIT3
      COMMON/JCON/JSTOP,JFLAG,jflag1
      LOGICAL TRANS,TRANS1,TRANS2,SSTATE
      COMMON/TRXY/EPS1,EPS2,EPS3,TRANS,TRANS1,TRANS2,SSTATE,MB9(99),NMB9
      LOGICAL RAD,BCIT,ETSIM,SEEP,ITSTOP,CIS,CIT,GRAV
      LOGICAL F7P,F11P,F8P,F9P,F6P,PRNT,o9p,o11p,o12p,o13p, &
      F14P,F15P,F16P,F17P,F18P,F19P
      COMMON/LOG1/RAD,BCIT,ETSIM,SEEP,ITSTOP,CIS,CIT,GRAV
      COMMON/LOG2/F7P,F11P,F8P,F9P,F6P,PRNT,o9p,o11p,o12p,o13p, &
      F14P,F15P,F16P,F17P,F18P,F19P
      CHARACTER*80 TITL
      CHARACTER*6 ZUNIT,CUNX,HUNX
      CHARACTER*7 TUNIT
      COMMON/SCHAR/TITL,ZUNIT,TUNIT,CUNX,HUNX
      LOGICAL HEAT,SOLUTE,FLOW
      COMMON /TRANSTYPE/HEAT,SOLUTE
      COMMON/TCON1/NIS,NIS1,NIS3
      COMMON/FLO/FLOW
      common/thick/dely
      COMMON/JCONF/JFLAG2
      double precision, allocatable, dimension(:,:) :: bcsol1
      double precision, allocatable, dimension(:) :: f1
      integer, allocatable, dimension(:) :: ibsol1, ibsol2
      SAVE STERR
      !!@@include 'd_ihdummAlloc.inc'
      allocate(IHDUM(NXR))
      !!@@include 'd_isdummAlloc.inc'
      allocate(ISDUM(NXR))
!-------------------------------------------------------------------
!
!   ADVANCE TO NEXT TIME STEP
!
      KTIM=KTIM+1
      IF (KTIM.NE.1.AND.JSTOP.NE.0) RETURN
      JSTOP=0
      JPLT=0
      NIT=0
      NIT1=0
      NIS1=0
      IF(KTIM.EQ.1) then
       kplt = 1
       do
        if(pltim(kplt).gt.stim) EXIT
        kplt = kplt + 1
       end do
      end if
      IF(JFLAG.EQ.1) THEN
!
!................................................................
!
!    READ DATA FOR NEW RECHARGE PERIOD
! ................................................................
!
      READ (05,*) TPER,DELT
!
!   CHECK FOR END OF SIMULATION
!
      jflag1 = 1
      jflag2 = 1
      IF(TPER.GE.999998.D0) THEN
      WRITE (06,4070) TMAX,STIM
      jstop=5
      return
      END IF
      READ (05,*) TMLT,DLTMX,DLTMIN,TRED
      KP=KP+1
      SSTATE=.FALSE.
      if(delt.lt.dltmin) then
       delt = dltmin
      else
       if(delt.gt.dltmx) delt = dltmx
      end if
      WRITE (06,4000) KP,TPER,TUNIT,DELT,TUNIT,TMLT,DLTMX,TUNIT,DLTMIN, &
      TUNIT,TRED
      READ (05,*) DSMAX,STERR
      READ (05,*) POND
      WRITE (06,4020) DSMAX,STERR,POND
      READ (05,*) PRNT
      READ (05,*) BCIT,ETSIM,SEEP
      WRITE (06,4010) PRNT,BCIT,ETSIM,SEEP
      DSMAX=DABS(DSMAX)
      ETOUT=0.0D0
      ETOUT1=0.0D0
!
!    READ SEEPAGE FACE DATA
!
      IF(SEEP) THEN
      READ (05,*) NFCS
      !!@@include 'd_spfcAlloc.inc'
      if (allocated(JSPX)) deallocate(JSPX)
      if (allocated(NFC)) deallocate(NFC)
      if (allocated(JLAST)) deallocate(JLAST)
      allocate(JSPX(3,NXR+NLY,NFCS))
      allocate(NFC(NFCS))
      allocate(JLAST(NFCS))
      DO 50 K=1,NFCS 
      READ (05,*) JJ,JLAST(K) 
      NFC(K)=JJ 
      READ (05,*) ((JSPX(L,J,K),L=2,3),J=1,JJ)
      DO 40 M=1,Nsol
      DO 40 J=1,JJ 
      J1=JSPX(2,J,K) 
      N1=JSPX(3,J,K) 
      N2=NLY*(N1-1)+J1 
      JSPX(1,J,K)=N2 
      Q(N2)=0.0D0 
      QQ(N2)=0.0D0
      IF(HEAT)THEN
         NHTYP(N2)=0
         TS(N2)=0.0D0
      END IF   
      IF(SOLUTE)THEN
        NCTYP(N2)=0
       CSS(M,N2)=0.0D0
      END IF 
       IF(J.GT.JLAST(K)) THEN 
       NTYP(N2)=3 
       ELSE 
       NTYP(N2)=1  
      IF(CS1.EQ.1.0D0) THEN
      Z1=DZZ(J1)
      ELSE
      Z1=DZZ(J1)*CS1+RX(N1)*CS2
      END IF
       P(N2)=-Z1 
       END IF
   40 CONTINUE 
   50 CONTINUE 
      END IF
!
!   READ IN NEW BOUNDARY CONDITIONS FOR RECHARGE PERIOD
!    IF IBC=0, POINT BOUNDARY CONDITIONS ARE READ IN.
!    IF IBC=1, LINE BOUNDARY CONDITIONS ARE READ IN, AND IT IS NECESSARY
!     TO SPECIFY FOUR POINTS ON THE LINE--THIS ALLOWS VERTICAL OR HORI-
!     ZONTAL LINES TO BE READ IN INDISCRIMINATELY.  THE SEQUENCE IS:
!     TOP ROW, BOTTOM ROW, LEFT COLUMN, RIGHT COLUMN, CODE, AND FLUX OR
!     PRESSURE HEAD FOR BOUNDARY CONDITION.
!
      READ (05,*) IBC 
      IF(IBC.GT.0) GO TO 80 
   70 IF (TRANS)THEN
      READ (05,*) JJ,NN,NTX,PFDUM
      IF(JJ.GE.999998) GO TO 130 
      IF(HEAT) THEN
      READ (05,*)NTT,TF
      ELSE
      NTT=0
      TF=0
      END IF
      IF(solute)  then
      READ (05,*)NTC,INSBC1,INSBC2,SBFRAC
      
      !#CALL SETUP_BOUNDARY_CONDITIONS(INSBC1,INSBC2,SBFRAC,BCSOL)
      allocate(bcsol1(1,nSol), ibsol1(1), ibsol2(1), f1(1))
      ibsol1(1) = insbc1
      ibsol2(1) = insbc2
      f1(1) = sbfrac
      status = RM_InitialPhreeqc2Concentrations(rm_id, bcsol1, 1, ibsol1, ibsol2, f1)
      do i = 1, nsol
          bcsol(i) = bcsol1(1,i)
      enddo
      deallocate(bcsol1, ibsol1, ibsol2, f1)
      
      ELSE
      NTC=0
      END IF
      ELSE
      READ (05,*) JJ,NN,NTX,PFDUM
      END IF
      IF(JJ.GE.999998) GO TO 130 
      JJT=JJ 
      JJB=JJ 
      NNL=NN 
      NNR=NN 
      GO TO 90 
  80  IF(TRANS)THEN
      READ(05,*) JJT,JJB,NNL,NNR,NTX,PFDUM
      IF(JJT.GE.999998) GO TO 130
      IF(HEAT) THEN
      READ (05,*)NTT,TF
      ELSE
      NTT=0
      TF=0.0d0
      END IF
      IF (SOLUTE)THEN
      READ (05,*)NTC,INSBC1,INSBC2,SBFRAC 
      
      !#CALL SETUP_BOUNDARY_CONDITIONS(INSBC1,INSBC2,SBFRAC,BCSOL)
      allocate(bcsol1(1,nSol), ibsol1(1), ibsol2(1), f1(1))
      ibsol1(1) = insbc1
      ibsol2(1) = insbc2
      f1(1) = sbfrac
      status = RM_InitialPhreeqc2Concentrations(rm_id, bcsol1, 1, ibsol1, ibsol2, f1)
      do i = 1, nsol
          bcsol(i) = bcsol1(1,i)
      enddo
      deallocate(bcsol1, ibsol1, ibsol2, f1)
      
      ELSE
      NTC=0
      END IF
      ELSE
      READ(05,*) JJT,JJB,NNL,NNR,NTX,PFDUM
      END IF 
!
  90  CONTINUE 
      IF (SOLUTE)THEN
      DO 92 JJ=JJT,JJB 
      DO 92 NN=NNL,NNR 
      DO 91 M=1,Nsol
      IN=NLY*(NN-1)+JJ
      CSS(M,IN)=BCSOL(M)
!
!  change made 99-12-16 so that ntc = 2 conductive heat flux is
!   in terms of energy per time per length of boundary (i.e.,
!   a line source) , as 
!   opposed to energy per time (which is for point source)
!     
!      DO 450 I=1, Nsol
!      BCSOL(I)=I
! 450  CONTINUE   
      if (ntc.eq.2) then
      area = dxr(nn)
      if(rad) area = pi2*rx(nn)*dxr(nn)
      CSS(M,IN) = BCSOL(M)*area
      end if
      IF(NTC.EQ.1) CC(M,IN)=BCSOL(M)
      NCTYP(IN)=NTC
  91  CONTINUE
  92  CONTINUE
      END IF
      DO 120 JJ=JJT,JJB 
      DO 120 NN=NNL,NNR 
      IN=NLY*(NN-1)+JJ 
      IF(HEAT) then
      TS(IN)=TF
      if (NTT.eq.2) then
      area = dxr(nn)
      if(rad) area = pi2*rx(nn)*dxr(nn)
      TS(IN) = Tf*area
      end if
      IF(NTT.EQ.1) TT(IN)=TF
      NHTYP(IN)=NTT
      END IF
!      if(ntx.eq.5.and.hx(in-1).gt.0.0d0) go to 80
      IF(NTX.NE.6) GO TO 100 
      NTYP(IN)=2 
      QQ(IN)=PFDUM 
      GO TO 120 
  100 NTYP(IN)= NTX 
      IF(NTX.EQ.4)NTYP(IN)=1 
      IF(NTX.EQ.0) WRITE (06,4040) JJ,NN 
      IF(CS1.EQ.1.0D0) THEN
      Z1=DZZ(JJ)
      ELSE
      Z1=DZZ(JJ)*CS1+RX(NN)*CS2
      END IF
      IF(NTX.EQ.1) P(IN)=PFDUM-Z1 
      IF(NTX.EQ.4) P(IN)=PFDUM 
      IF(NTX.EQ.2) GO TO 110 
      QQ(IN)=0.0d0 
!
!  modifications for gravity drainage BC
!
      if (ntx.eq.7) then
       if(hx(in+1).gt.0.d0.or.hx(in-1).le.0.d0) then
        WRITE(6,4012)  JJ,NN
        ntyp(in)=0
       else
!        nctyp(in) = 7
        ntyp(in) = 7
       end if
      end if
!
!  end modifications
! 
       GO TO 120 
  110 CONTINUE 
!  SET QQ TO RAINFALL RATE 
      AREA=DXR(NN) 
      IF(RAD)AREA=PI2*RX(NN)*DXR(NN) 
      QQ(IN)=PFDUM*AREA 
  120 CONTINUE 
      IF(IBC.EQ.0) GO TO 70 
      GO TO 80 
  130 CONTINUE
!      if (SOLUTE)then
!      do  I=1, Nsol
!      WRITE (6,*)'BCSOL(',I,')=',BCSOL(I)
!      END DO
!      END IF
      write(6,*)"temerature setting at the boundary"
!      CALL VSOUT(1,TT)
!      CALL VSOUTS(1,CC)
!
!     WRITE INITIAL BOUNDARY CONDITIONS FOR THIS PERIOD
!
      GRAV = .FALSE.
      WRITE (06,4040) KP
      DO 111 J=1,NLY
      DO 109 N=1,NXR
      IN=NLY*(N-1)+J
      Q(IN)=0.0D0
      if(ntyp(in).eq.7) GRAV = .TRUE.
 109  IDUM(N)=NTYP(IN)
  111 WRITE (06,4050) J,(IDUM(I),I=1,NXR)
      IF(HEAT) THEN
      DO 151 J=1,NLY 
      DO 141 N=1,NXR 
      IN=NLY*(N-1)+J 
      Q(IN)=0.0D0 
  141 IHDUM(N)= NHTYP(IN)
!      WRITE (06,4081) J,(IHDUM(I),I=1,NXR)
 151  continue
      END IF
      IF(SOLUTE)THEN
       DO 152 J=1,NLY 
       DO 142 N=1,NXR 
       IN=NLY*(N-1)+J 
       Q(IN)=0.0D0 
  142 ISDUM(N)= NCTYP(IN)
!   WRITE (06,4081) J,(ISDUM(I),I=1,NXR)
  152 continue
      END IF
      TMPX=STIM+TPER
      IF(TMPX+0.5D0*DLTMIN.GT.TMAX) TMPX=TMAX
!
!   CALCULATE NEW COEFFICIENTS
!
      IF(KTIM.NE.1)CALL VSCOEF
      END IF
!
!   INITIALIZE REQUIRED ARRAYS FOR NEW BOUNDARY CONDITION, UPDATE
!   PXXX,THLST.  COMPUTE MAXIMUM HEAD CHANGE DURING LAST TIME STEP
!
      PDIF=0.0D0
      IF(.NOT.SSTATE) THEN
      DO 121 J=2,NLYY
      DO 121 N=2,NXRR
      IN=NLY*(N-1)+J
      IF(HX(IN).EQ.0.0D0) GO TO 121
      P12=P(IN)-PXXX(IN)
      PTMP=DABS(P12)
      IF(PTMP.GT.PDIF)PDIF=PTMP
      PXXX(IN)=P(IN)
      THLST(IN)=THETA(IN)
      IF(HEAT)TTOLD(IN)=TT(IN)
      IF(SOLUTE)THEN
      DO 119 M=1,Nsol   
      CCOLD(M,IN)=CC(M,IN) 
  119 CONTINUE
      END IF
  121 CONTINUE
!
!    CHECK FOR STEADY STATE
!
      IF(jflag.ne.1.and.PDIF.LE.STERR) THEN
      SSTATE=.TRUE.
      WRITE(6,4060) STIM,KTIM
      END IF
      END IF
      JFLAG=0
!
!   INITIALIZE DHMX
!
      DO 131 K=1,itmax
  131 DHMX(K)=0.0D0
!
!    ADVANCE DELT AND RESET TO PROPER LENGTH IF NECESSARY
!
      if (delt.lt.dltmin) delt = dltmin
      DLTOLD=DELT
      DELT= TMLT*DELT
!
!    MAXIMUM PERMISSABLE HEAD CHANGE CHECK
!
      IF(KTIM.GE.2) THEN
      IF((PDIF*DELT/DLTOLD).GT.DSMAX)DELT=DLTOLD*DSMAX*0.98D0/PDIF
      END IF
      T1=DMIN1(TMPX,PLTIM(KPLT))
      T2=T1-STIM
!
!  changes made 6-12-02 for calculating delt.  This new
!  version will allow delt<dltmin only to match obs times
!  or end of recharge period.
!  THESE NEED TO BE CHECKED CAREFULLY
!
!      IF(DELT.GT.(T2-DLTMIN)) DELT=T2
!      IF(DELT.LT.DLTMIN)DELT=DLTMIN
      if(delt.gt.t2) then
       delt = t2
      else
       if(delt.lt.dltmin) delt = dltmin
      end if
!      IF(DELT.GT.DLTMX)DELT=DLTMX
       if(delt-dltmx.ge.0.000001D0*dltmin) delt = dltmx
!      IF(T1.NE.PLTIM(KPLT).OR.T2-DELT.GT.0.5D0*DLTMIN) GO TO 140
      IF(T1.NE.PLTIM(KPLT).or.t2-delt.gt.0.d0) GO TO 140
      KPLT=KPLT+1
      JPLT=1
!  140 IF(DELT.LT.DLTMIN)DELT=DLTMIN
 140  continue
      STIM=STIM+DELT
!      IF (TMPX-STIM.LT.0.5D0*DLTMIN) JFLAG=1
!      IF(TMAX-STIM.LT.0.5D0*DLTMIN) THEN
!      IF (TMPX-STIM.LT.0.000001D0*DLTMIN) JFLAG=1
      IF (TMPX-STIM.LT.0.000001D0*DLTMIN) then
       JFLAG=1
       JPLT=1
       delt = delt + (tmpx - stim)
       stim = tmpx
       do
        if (stim.lt.pltim(kplt)) exit
        kplt = kplt + 1
       end do
      end if
      IF(TMAX-STIM.LT.0.000001*DLTMIN) THEN
!
!  end changes of 6-12-02
!
      JSTOP=1
      JPLT=1
      ELSE
      IF(KTIM.GT.NUMT) THEN
      JSTOP=8
      JPLT=1
      PRINT*,'Maximum number of time steps exceeded' &
            , ' Simulation terminated'
      WRITE(6,4080)
      END IF
      END IF
      !!@@include 'd_ihdummDealloc.inc'
      deallocate(IHDUM)
      !!@@include 'd_isdummDealloc.inc'
      deallocate(ISDUM)
      RETURN
 4000 FORMAT(6X,'DATA FOR RECHARGE PERIOD ',I9//10X, &
      23HLENGTH OF THIS PERIOD =,1PE14.5,1X,A4,/10X, &
      45HLENGTH OF INITIAL TIME STEP FOR THIS PERIOD =,1PE14.5,1X,A4/ &
      10X,27HMULTIPLIER FOR TIME STEP = ,1PE10.3,/10X, &
      25HMAXIMUM TIME STEP SIZE = ,1PE14.5,1X,A4/10X, &
      25HMINIMUM TIME STEP SIZE = ,1PE14.5,1X,A4, &
      /10X,'TIME STEP REDUCTION FACTOR = ',1PE10.3)
 4010 FORMAT(15X,37HPRINT SOLUTION AFTER EVERY TIME STEP?,1X,L1/ &
      15X,'SIMULATE EVAPORATION? ',L1/ &
      15X,29HSIMULATE EVAPOTRANSPIRATION? ,L1/ &
      15X,24HSIMULATE SEEPAGE FACES? ,L1/)
 4012 format(16x,'WARNING -- GRAVITY BOUNDARY NODE MUST LIE ABOVE ',  &
      'AN INACTIVE NODE.'/16X,'AND BELOW AN ACTIVE NODE.'/16X, &
      'GRAVITY BOUNDARY NOT APPLIED FOR CELL: ' &
      ,2I6/)
 4020 FORMAT( &
      15X,55HMAXIMUM PRESSURE HEAD CHANGE ALLOWED IN ONE TIME STEP =, &
      F8.3/15X,'STEADY-STATE CLOSURE CRITERION = ',1PE10.3/ &
      15X,'MAXIMUM DEPTH OF PONDING = ',1PE10.3)
 4030 FORMAT(1X,'******** WARNING --- NODE TYPE OF 0 ASSIGNED TO BO',  &
      'UNDARY NODE ',2I5)
 4040 FORMAT(6X,41HNODE TYPE AND INITIAL BOUNDARY CONDITIONS, &
      12H FOR PERIOD ,I9/6X,8HLEGEND: /15X,17H0 = INTERIOR CELL/ &
      15X,32H1 = SPECIFIED PRESSURE HEAD CELL/15X, &
      23H2 = SPECIFIED FLUX CELL/ &
       15X,31H3 = POTENTIAL SEEPAGE FACE NODE/ &
       15X,43H5 = NODE FOR WHICH EVAPORATION IS PERMITTED/ &
       15x,'7 = GRAVITY DRAIN CELL'/) 
 4050 FORMAT(1H ,I5,5X,100(99999I1))
 4060 FORMAT(6X,100(1H*)/5X, &
      'STEADY STATE REACHED AT TIME = ',E14.6,'   TIME STEP NUMBER = ' &
      ,I9//)
 4070 FORMAT(6X,100(1H*),/,5X,17HEND OF SIMULATION/,  &
      5X,33HMAXIMUM SIMULATION TIME (TMAX) = ,E15.6/, &
      5X,33HELAPSED SIMULATION TIME (STIM) = ,E15.6/, &
      6X,100(1H*))
 4080 FORMAT(' Maximum number of time steps exceeded'/ &
      ' Simulation terminated')
 4081 FORMAT(1H ,I5,5X,80I1)      
      END
     SUBROUTINE VSMGEN
!******
!VSMGEN
!******
!
!    PURPOSE:  TO SET UP COEFFICIENT MATRICES AND CALL
!          SOLUTION ALGORITHM
!
!-----------------------------------------------------------------------
!
!   SPECIFICATIONS FOR ARRAYS AND SCALARS
!
      use rspac
      use kcon
      use mprop
      use press
      use disch
      use hcon
      use equat
      use jtxx
      use ptet
      use pit
      use plott
      use rpropsh
      use scon
      use equats
      use temp
      IMPLICIT DOUBLE PRECISION (A-H,P-Z)

      COMMON/ISPAC/NLY,NLYY,NXR,NXRR,NNODES,Nsol,Nodesol
      COMMON/WGT/WUS,WDS
      COMMON/SCN1/TMPX,TMLT,DLTMX,DLTMIN,TRED
      COMMON/TCON/STIM,DSMAX,KTIM,NIT,NIT1,KP,NIT3
      COMMON/JCON/JSTOP,JFLAG,jflag1
      LOGICAL RAD,BCIT,ETSIM,SEEP,ITSTOP,CIS,CIT,GRAV
      COMMON/LOG1/RAD,BCIT,ETSIM,SEEP,ITSTOP,CIS,CIT,GRAV
      CHARACTER*80 TITL
      CHARACTER*6 ZUNIT,CUNX,HUNX
      CHARACTER*7 TUNIT
      COMMON/SCHAR/TITL,ZUNIT,TUNIT,CUNX,HUNX
      LOGICAL HEAT,SOLUTE,FLOW
      COMMON/TRANSTYPE/HEAT,SOLUTE
      integer hydraulicFunctionType
      common/functiontype/ hydraulicFunctionType
      COMMON/TCON1/NIS,NIS1,NIS3
      COMMON/FLO/FLOW
      COMMON/SCON1/ITESTS
!
! ......................................................................
!  START OF LINEARIZATION ITERATION LOOP
! .....................................................................
!
!    UPDATE COEFFICIENTS
!
      I13=0
!
!     ESTABLISH TIME-DEPENDENT PARAMETERS GOVERNING EVAPORATION AND
!     TRANSPIRATION.  DETERMINE ROOT ACTIVITY.
!
   10 IF ( BCIT.OR. ETSIM) THEN
      CALL VSPET
      DO 20 J=2,NLYY
      DO 20 I=2,NXRR
      N=NLY*(I-1)+J
      IF(HX(N).GT.0.0D0) THEN
      IF(ETSIM) RT(N)=VSRDF(DPTH(N),DELZ(J))
      Q(N)=0.0D0
      END IF
   20 CONTINUE
      END IF
   30 IF (NIT.NE.0) CALL VSCOEF
!
! --------------------  UPDATE BOUNDARY AND FLUX CONDITIONS ------------
!
      IF(BCIT)CALL VSEVAP
      IF (ETSIM)CALL VSPLNT
      IF(SEEP) CALL VSSFAC
      if(GRAV.and.nit.eq.0) CALL vsgrav_dr
!
! .....................................................................
!
!         LOOP TO CALCULATE COEFFICIENT MATRIX
! .....................................................................
!
      DO 40 J=2,NLYY
      DO 40 I=2,NXRR
      N=NLY*(I-1)+J
      IF(HX(N).GT.0.0D0) THEN
      JM1=N-1
      JP1=N+1
      IM1=N-NLY
      IP1=N+NLY
      VOL=DXR(I)*DELZ(J)
      IF(RAD)VOL=PI2*RX(I)*DXR(I)*DELZ(J)
      JJ=JTEX(N)
!
!   CALCULATE STORAGE TERMS
!
      IF(CS1.EQ.1.0D0) THEN
      Z1=DZZ(J)
      ELSE
      Z1=DZZ(J)*CS1+RX(I)*CS2
      END IF
      PTMP=P(N)+Z1
      if(hydraulicFunctionType.eq.1) then
       SCAP=VSDTHUVG(PTMP,JJ)
      else
       if(hydraulicFunctionType.eq.2) then
        SCAP=VSDTHUHK(PTMP,JJ)
       else
        if(hydraulicFunctionType.eq.0) then
         SCAP=VSDTHUBC(PTMP,JJ)
        else
         if(hydraulicFunctionType.eq.3) then
          SCAP=VSDTHUTAB(PTMP,JJ)
         else
          SCAP=VSDTHUOT(PTMP,JJ)
         end if
        end if
       end if
      end if
      if(HEAT)THEN
      GSF=VOL*SCAP*RHO(N)
      else
      GSF=VOL*SCAP
      END IF 
      if (HK(JJ,3).ne. 0.0D0) then
       SS=HK(JJ,2)/HK(JJ,3)
      else
       SS=0.0D0
      end if
      IF (HEAT) THEN
      GSS=VOL*THETA(N)*SS*RHO(N)
      ELSE
      GSS=VOL*THETA(N)*SS
      END IF
      G1=0.0D0
!
!   APPLY NEWTON-RAPHSON LINEARIZATION TO STORAGE TERM.
!   PITT HOLDS STORAGE TERMS FROM PREVIOUS ITERATION.
!
      IF(NIT.GT.0.AND.XI(N).NE.0.0D0) G1=(P(N)-PXXX(N))*&
                                        (GSF+GSS-PITT(N))/XI(N)
      PITT(N)=GSF+GSS
      G1=-G1/DELT
      GSF=-GSF/DELT
      GSS=-GSS/DELT
      IF(WUS.EQ.0.0D0) THEN
!
!   USE GEOMETRIC MEAN OR WEIGHTS FOR INTERCELL K
!     
      IF(HEAT)THEN
      A(N)=HKLL(N)*DSQRT(HCND(IM1)*RHO(IM1)*HCND(N)*RHO(N))
      B(N)=HKTT(N)*DSQRT(HCND(JM1)*RHO(JM1)*HCND(N)*RHO(N))
      C(N)=HKLL(IP1)*DSQRT(HCND(IP1)*RHO(IP1)*HCND(N)*RHO(N))
      D(N)=HKTT(JP1)*DSQRT(HCND(JP1)*RHO(JP1)*HCND(N)*RHO(N))
      ELSE
      A(N)=HKLL(N)*DSQRT(HCND(IM1)*HCND(N))
      B(N)=HKTT(N)*DSQRT(HCND(JM1)*HCND(N))
      C(N)=HKLL(IP1)*DSQRT(HCND(IP1)*HCND(N))
      D(N)=HKTT(JP1)*DSQRT(HCND(JP1)*HCND(N))
      END IF
      ELSE
!
!  CHOOSE UPSTREAM WEIGHTING COEFFICIENTS
!
      IF(P(IM1).LE.P(N).OR.HX(IM1).EQ.0.0D0) THEN
      ALA=WDS
      BTA=WUS
      ELSE
      ALA=WUS
      BTA=WDS
      END IF
      IF(P(JM1).LE.P(N).OR.HX(JM1).EQ.0.0D0) THEN
      ALB=WDS
      BTB=WUS
      ELSE
      ALB=WUS
      BTB=WDS
      END IF
      IF(P(IP1).LE.P(N).OR.HX(IP1).EQ.0.0D0) THEN
      ALC=WDS
      BTC=WUS
      ELSE
      ALC=WUS
      BTC=WDS
      END IF
      IF(P(JP1).LE.P(N).OR.HX(JP1).EQ.0.0D0) THEN
      ALD=WDS
      BTD=WUS
      ELSE
      ALD=WUS
      BTD=WDS
      END IF
!
!   SET THE PENTA-DIAGNOL COEFFICIENT MATRIX (E IS MAIN DIAGNOL)
!   AND RIGHT HAND SIDE
!
      IF(HEAT)THEN
      A(N)=(ALA*HCND(IM1)*RHO(IM1)+BTA*HCND(N)*RHO(N))*HKLL(N)
      B(N)=(ALB*HCND(JM1)*RHO(JM1)+BTB*HCND(N)*RHO(N))*HKTT(N)
      C(N)=(ALC*HCND(IP1)*RHO(IP1)+BTC*HCND(N)*RHO(N))*HKLL(IP1)
      D(N)=(ALD*HCND(JP1)*RHO(JP1)+BTD*HCND(N)*RHO(N))*HKTT(JP1)
      ELSE
      A(N)=(ALA*HCND(IM1)+BTA*HCND(N))*HKLL(N)
      B(N)=(ALB*HCND(JM1)+BTB*HCND(N))*HKTT(N)
      C(N)=(ALC*HCND(IP1)+BTC*HCND(N))*HKLL(IP1)
      D(N)=(ALD*HCND(JP1)+BTD*HCND(N))*HKTT(JP1)
      END IF
      END IF
      if(ntyp(n).eq.1) then
       if(ntyp(im1).eq.1) a(n) = 0.0d0
       if(ntyp(jm1).eq.1) b(n) = 0.0d0
       if(ntyp(ip1).eq.1) c(n) = 0.0d0
       if(ntyp(jp1).eq.1) d(n) = 0.0d0
      end if
      E(N)=-A(N)-B(N)-C(N)-D(N)
      IF(HEAT)THEN
      RHS(N)=VOL*(THETA(N)*RHO(N)-THLST(N)*RHOOLD(N))/DELT-&
      (Q(N)+QQ(N))*RHO(N)-(A(N)*P(IM1)+B(N)*P(JM1)+ &
      C(N)*P(IP1)+D(N)*P(JP1)+(E(N)+GSS)*P(N))+GSS*PXXX(N) 
      ELSE    
      RHS(N)=VOL*(THETA(N)-THLST(N))/DELT-(Q(N)+QQ(N))-(A(N)*P(IM1)+B(N)&
      *P(JM1)+C(N)*P(IP1)+D(N)*P(JP1)+(E(N)+GSS)*P(N))+GSS*PXXX(N)
      END IF
      E(N)=E(N)+GSF+GSS+G1
      END IF
   40 CONTINUE
!
!    CALL SOLUTION ALGORITHM
!
      NIT=NIT+1
      CALL SLVSIP
      IF(NIT.LT.MINIT) GO TO 30
!
!   IF SOLUTION HAS BEEN FOUND THEN RETURN
!
      IF(ITEST.EQ.0) RETURN
      IF(NIT.LE.ITMAX) GO TO 30
!
!   MAXIMUM NUMBER OF ITERATIONS EXCEEDED
!   
      PRINT*,'ERROr: EXCEEDED PERMITTED NUMBER OF ITERATIONS'
      WRITE (6,4000) NIT,KTIM,STIM,TUNIT
!
!   AUTOMATICALLY REDUCE TIME STEP SIZE, BUT NOT MORE
!   THAN TWICE.
!
      IF(DELT.LE.DLTMIN.OR.I13.GT.2.OR.TRED.LE.0.0D0) THEN
      IF(.NOT.ITSTOP)RETURN
!
!   TERMINATE SIMULATION.
!
      JSTOP=9
      JFLAG=1
      WRITE(6,4020)
      RETURN
      ELSE
      I13=I13+1
      DELTT=DELT*TRED
      IF(DELTT.LT.DLTMIN) DELTT=DLTMIN
      if(delt-deltt.ge.dltmin) then
       jflag = 0
       if(jstop.eq.1) then
        jstop = 0
        jplt = 0
       else
        if(jplt.eq.1) then
         jplt = 0
         if(stim.eq.pltim(kplt)) kplt = kplt - 1
        end if
       end if
      end if
      WRITE(6,4010) DELTT
      STIM=STIM-DELT+DELTT
      DELT=DELTT
!
!   RESET HEADS TO VALUES AT END OF PREVIOUS TIME STEP.
!
      DO 50 II=1,NNODES
      IF(NTYP(II).NE.1.AND.HX(II).GT.0.0D0) P(II)=PXXX(II)
   50 CONTINUE
      NIT=1
      GO TO 10
      END IF
 4000 FORMAT(5X,100(1H*)/5X,'EXCEEDED PERMITTED NUMBER OF ITERATIONS', &
      '  ( =',I9,')' &
       /5X,'TIME STEP NUMBER',I9/5X,'ELAPSED TIME = ', &
       1PE14.5,1X,A4  /5X,100(1H*))
 4010 FORMAT(5X,'TIME STEP SIZE REDUCED TO ',E14.6)
 4020 FORMAT('Simulation terminated')
      END
