/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vs2_vs2drt */

#ifndef _Included_vs2_vs2drt
#define _Included_vs2_vs2drt
#ifdef __cplusplus
extern "C" {
#endif
#undef vs2_vs2drt_COMPUTATIONAL
#define vs2_vs2drt_COMPUTATIONAL 1L
#undef vs2_vs2drt_PLAYBACK_BINARY
#define vs2_vs2drt_PLAYBACK_BINARY 2L
/*
 * Class:     vs2_vs2drt
 * Method:    start
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_start
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     vs2_vs2drt
 * Method:    getDoTransport
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vs2_vs2drt_getDoTransport
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    getDoEnergyTransport
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vs2_vs2drt_getDoEnergyTransport
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    getDoSoluteTransport
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vs2_vs2drt_getDoSoluteTransport
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    advanceOneStep
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vs2_vs2drt_advanceOneStep
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    getJStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vs2_vs2drt_getJStop
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    getNumCellAlongX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vs2_vs2drt_getNumCellAlongX
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    getNumCellAlongZ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vs2_vs2drt_getNumCellAlongZ
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    getCellSizesAlongX
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getCellSizesAlongX
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getCellSizesAlongZ
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getCellSizesAlongZ
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getTransport
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getTransport
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getTemperature
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getTemperature
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getConcentration
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getConcentration
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getComponentCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vs2_vs2drt_getComponentCount
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    getComponents
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_vs2_vs2drt_getComponents
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    getMoistureContent
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getMoistureContent
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getSaturation
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getSaturation
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getPressureHead
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getPressureHead
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getKSat
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getKSat
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getTexturalClassArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getTexturalClassArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getVx
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getVx
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getVz
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getVz
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getTimeStep
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vs2_vs2drt_getTimeStep
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    getModelTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_vs2_vs2drt_getModelTime
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    getFlowMassBalanceErrors
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getFlowMassBalanceErrors
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getTransportMassBalanceErrors
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getTransportMassBalanceErrors
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getHeatTransportMassBalanceErrors
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getHeatTransportMassBalanceErrors
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     vs2_vs2drt
 * Method:    getSoluteTransportMassBalanceErrors
 * Signature: (I[D)V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_getSoluteTransportMassBalanceErrors
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     vs2_vs2drt
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     vs2_vs2drt
 * Method:    releaseMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vs2_vs2drt_releaseMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
